-- ODM-CMMS PostgreSQL Schema — 001_core.sql
-- Generated from MySQL historical schema reference + repository drift


CREATE TABLE IF NOT EXISTS organizations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subscription_id INTEGER DEFAULT NULL,
    organization_name varchar(255) NOT NULL,
    industry varchar(50) DEFAULT 'other',
    subscription_plan varchar(50) DEFAULT 'basic',
    subscription_status varchar(50) DEFAULT 'active',
    billing_email varchar(100) DEFAULT NULL,
    billing_address text,
    max_users INTEGER DEFAULT '10',
    max_facilities INTEGER DEFAULT '5',
    max_equipment INTEGER DEFAULT '100',
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    phone varchar(50) DEFAULT NULL,
    logo_url varchar(500) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS industries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(50) NOT NULL,
    name varchar(255) NOT NULL,
    description text,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_industries_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS organization_industries (
    organization_id INTEGER NOT NULL,
    industry_id INTEGER NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (organization_id, industry_id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(50) NOT NULL,
    email varchar(100) NOT NULL,
    password_hash varchar(255) NOT NULL,
    full_name varchar(100) NOT NULL,
    phone varchar(20) DEFAULT NULL,
    role VARCHAR(100) DEFAULT 'operator' CONSTRAINT chk_users_role CHECK (role IN ('admin','operator','supervisor')),
    facility_id INTEGER DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    status VARCHAR(100) DEFAULT 'active' CONSTRAINT chk_users_status CHECK (status IN ('invited','active','suspended','archived')),
    is_billable BOOLEAN DEFAULT TRUE,
    invited_by INTEGER DEFAULT NULL,
    invited_at TIMESTAMPTZ NULL DEFAULT NULL,
    last_login TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    is_organization_admin BOOLEAN DEFAULT FALSE,
    is_sso_user BOOLEAN DEFAULT FALSE,
    sso_provider varchar(50) DEFAULT NULL,
    last_sso_login_at TIMESTAMPTZ NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS facilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    code varchar(20) NOT NULL,
    description text,
    address text,
    city varchar(50) DEFAULT NULL,
    state varchar(50) DEFAULT NULL,
    zip_code varchar(20) DEFAULT NULL,
    country varchar(50) DEFAULT 'USA',
    status VARCHAR(100) DEFAULT 'active' CONSTRAINT chk_facilities_status CHECK (status IN ('active','inactive','under_maintenance')),
    manager_id INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    facility_type VARCHAR(100) NOT NULL DEFAULT 'OTHER' CONSTRAINT chk_facilities_facility_type CHECK (facility_type IN ('WTP','WWTP','WPS','WWLS','RESERVOIR','BOOSTER_STATION','ADMIN_BUILDING','OTHER')),
    sap_reference_code varchar(50) DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    default_operator_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_facilities_code UNIQUE (code),
    CONSTRAINT uq_facilities_uniq_facility_code_org UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS invitations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    email varchar(255) NOT NULL,
    role VARCHAR(100) DEFAULT 'operator' CONSTRAINT chk_invitations_role CHECK (role IN ('operator','supervisor','admin')),
    invited_by INTEGER NOT NULL,
    token varchar(255) NOT NULL,
    status VARCHAR(100) DEFAULT 'pending' CONSTRAINT chk_invitations_status CHECK (status IN ('pending','accepted','expired','cancelled')),
    expires_at TIMESTAMPTZ NOT NULL,
    accepted_at TIMESTAMPTZ NULL DEFAULT NULL,
    accepted_by_user_id INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_invitations_token UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    title varchar(200) NOT NULL,
    message text,
    notification_type varchar(50) DEFAULT 'info',
    entity_type varchar(50) DEFAULT NULL,
    entity_id INTEGER DEFAULT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMPTZ NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dashboard_widgets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    widget_type varchar(50) NOT NULL,
    widget_config JSONB DEFAULT NULL,
    sort_order INTEGER DEFAULT '0',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sso_configurations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    provider_type VARCHAR(100) NOT NULL CONSTRAINT chk_sso_configurations_provider_type CHECK (provider_type IN ('saml','oidc','azure_ad','google_workspace','okta')),
    provider_name varchar(100) NOT NULL,
    saml_entity_id varchar(500) DEFAULT NULL,
    saml_idp_sso_url varchar(500) DEFAULT NULL,
    saml_idp_slo_url varchar(500) DEFAULT NULL,
    saml_idp_certificate text,
    saml_sp_entity_id varchar(500) DEFAULT NULL,
    saml_sp_acs_url varchar(500) DEFAULT NULL,
    saml_name_id_format varchar(100) DEFAULT 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    oidc_client_id varchar(200) DEFAULT NULL,
    oidc_client_secret varchar(500) DEFAULT NULL,
    oidc_authorization_endpoint varchar(500) DEFAULT NULL,
    oidc_token_endpoint varchar(500) DEFAULT NULL,
    oidc_userinfo_endpoint varchar(500) DEFAULT NULL,
    oidc_jwks_uri varchar(500) DEFAULT NULL,
    oidc_scopes varchar(200) DEFAULT 'openid email profile',
    email_attribute varchar(100) DEFAULT 'email',
    first_name_attribute varchar(100) DEFAULT 'firstName',
    last_name_attribute varchar(100) DEFAULT 'lastName',
    groups_attribute varchar(100) DEFAULT NULL,
    role_attribute varchar(100) DEFAULT NULL,
    require_signed_assertions BOOLEAN DEFAULT TRUE,
    require_encrypted_assertions BOOLEAN DEFAULT FALSE,
    signature_algorithm varchar(50) DEFAULT 'rsa-sha256',
    auto_provision_users BOOLEAN DEFAULT FALSE,
    default_role varchar(20) DEFAULT 'operator',
    default_facility_id INTEGER DEFAULT NULL,
    session_duration_minutes INTEGER DEFAULT '480',
    enforce_sso_only BOOLEAN DEFAULT FALSE,
    is_enabled BOOLEAN DEFAULT FALSE,
    is_configured BOOLEAN DEFAULT FALSE,
    last_tested_at TIMESTAMPTZ NULL DEFAULT NULL,
    last_test_result JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_sso_configurations_organization_id UNIQUE (organization_id)
);

CREATE TABLE IF NOT EXISTS sso_user_mappings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    external_user_id varchar(200) NOT NULL,
    external_email varchar(200) NOT NULL,
    provider_type varchar(50) NOT NULL,
    last_login_at TIMESTAMPTZ NULL DEFAULT NULL,
    login_count INTEGER DEFAULT '0',
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_sso_user_mappings_uk_org_external UNIQUE (organization_id, external_user_id)
);

CREATE TABLE IF NOT EXISTS sso_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    sso_config_id INTEGER NOT NULL,
    session_token varchar(500) NOT NULL,
    idp_session_id varchar(200) DEFAULT NULL,
    ip_address varchar(45) DEFAULT NULL,
    user_agent text,
    started_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ NULL DEFAULT NULL,
    ended_reason varchar(50) DEFAULT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE organization_industries ADD CONSTRAINT fk_organization_industries_organization_industries_ibfk_1 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE organization_industries ADD CONSTRAINT fk_organization_industries_organization_industries_ibfk_2 FOREIGN KEY (industry_id) REFERENCES industries(id) ON DELETE CASCADE;
ALTER TABLE users ADD CONSTRAINT fk_users_fk_user_facility FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE users ADD CONSTRAINT fk_users_fk_users_facility_mig FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE SET NULL;
ALTER TABLE facilities ADD CONSTRAINT fk_facilities_facilities_ibfk_1 FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE facilities ADD CONSTRAINT fk_facilities_fk_facilities_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE facilities ADD CONSTRAINT fk_facilities_fk_facilities_default_operator_mig FOREIGN KEY (default_operator_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE invitations ADD CONSTRAINT fk_invitations_invitations_ibfk_1 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE invitations ADD CONSTRAINT fk_invitations_invitations_ibfk_2 FOREIGN KEY (invited_by) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE sso_configurations ADD CONSTRAINT fk_sso_configurations_sso_configurations_ibfk_1 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE sso_configurations ADD CONSTRAINT fk_sso_configurations_sso_configurations_ibfk_2 FOREIGN KEY (default_facility_id) REFERENCES facilities(id) ON DELETE SET NULL;
ALTER TABLE sso_user_mappings ADD CONSTRAINT fk_sso_user_mappings_sso_user_mappings_ibfk_1 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE sso_user_mappings ADD CONSTRAINT fk_sso_user_mappings_sso_user_mappings_ibfk_2 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE sso_sessions ADD CONSTRAINT fk_sso_sessions_sso_sessions_ibfk_1 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE sso_sessions ADD CONSTRAINT fk_sso_sessions_sso_sessions_ibfk_2 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE sso_sessions ADD CONSTRAINT fk_sso_sessions_sso_sessions_ibfk_3 FOREIGN KEY (sso_config_id) REFERENCES sso_configurations(id) ON DELETE CASCADE;
