-- ODM-CMMS PostgreSQL Schema — 002_equipment_taxonomy.sql
-- Generated from MySQL historical schema reference + repository drift


CREATE TABLE IF NOT EXISTS equipment_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_code varchar(50) NOT NULL,
    category_name varchar(255) NOT NULL,
    description text,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_equipment_categories_category_code UNIQUE (category_code)
);

CREATE TABLE IF NOT EXISTS equipment_classes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id INTEGER NOT NULL,
    class_code varchar(50) NOT NULL,
    class_name varchar(255) NOT NULL,
    description text,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_equipment_classes_unique_class_per_category UNIQUE (category_id, class_code)
);

CREATE TABLE IF NOT EXISTS equipment_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_id INTEGER NOT NULL,
    type_code varchar(50) NOT NULL,
    type_name varchar(255) NOT NULL,
    description text,
    typical_components text,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_equipment_types_unique_type_per_class UNIQUE (class_id, type_code)
);

CREATE TABLE IF NOT EXISTS equipment_type_industries (
    equipment_type_id INTEGER NOT NULL,
    industry_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    criticality VARCHAR(100) DEFAULT 'B' CONSTRAINT chk_equipment_type_industries_criticality CHECK (criticality IN ('A','B','C')),
    PRIMARY KEY (equipment_type_id, industry_id)
);

CREATE TABLE IF NOT EXISTS subunits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    subunit_code varchar(50) NOT NULL,
    subunit_name varchar(255) NOT NULL,
    description text,
    typical_failures text,
    maintenance_instructions text,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_subunits_unique_subunit_per_type UNIQUE (equipment_type_id, subunit_code)
);

CREATE TABLE IF NOT EXISTS equipment_subunits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    subunit_code varchar(50) NOT NULL,
    subunit_name varchar(255) NOT NULL,
    description text,
    typical_failures text,
    maintenance_instructions text,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_equipment_subunits_unique_subunit_per_type UNIQUE (equipment_type_id, subunit_code)
);

CREATE TABLE IF NOT EXISTS maintainable_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subunit_id INTEGER NOT NULL,
    item_code varchar(50) NOT NULL,
    item_name varchar(255) NOT NULL,
    description text,
    typical_components text,
    spare_part_reference varchar(100) DEFAULT NULL,
    criticality varchar(20) DEFAULT 'medium',
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_maintainable_items_unique_item_per_subunit UNIQUE (subunit_id, item_code)
);

CREATE TABLE IF NOT EXISTS object_parts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_class_id INTEGER NOT NULL,
    object_part_code varchar(20) NOT NULL,
    object_part_name varchar(255) NOT NULL,
    description text,
    iso_reference varchar(50) DEFAULT NULL,
    typical_location text,
    inspection_points text,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_object_parts_unique_part_per_class UNIQUE (equipment_class_id, object_part_code)
);

CREATE TABLE IF NOT EXISTS damage_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_class_id INTEGER NOT NULL,
    damage_code varchar(20) NOT NULL,
    damage_name varchar(255) NOT NULL,
    description text,
    iso_failure_mode_reference varchar(50) DEFAULT NULL,
    typical_symptoms text,
    severity_level VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_damage_codes_severity_level CHECK (severity_level IN ('low','medium','high','critical')),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_damage_codes_unique_damage_per_class UNIQUE (equipment_class_id, damage_code)
);

CREATE TABLE IF NOT EXISTS cause_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_class_id INTEGER DEFAULT NULL,
    cause_code varchar(20) NOT NULL,
    cause_name varchar(255) NOT NULL,
    description text,
    iso_failure_cause_reference varchar(50) DEFAULT NULL,
    cause_category VARCHAR(100) DEFAULT 'unknown' CONSTRAINT chk_cause_codes_cause_category CHECK (cause_category IN ('design','manufacturing','operation','maintenance','human_error','environmental','material','unknown')),
    is_preventable BOOLEAN DEFAULT TRUE,
    prevention_guidelines text,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_cause_codes_unique_cause_code UNIQUE (cause_code)
);

CREATE TABLE IF NOT EXISTS activity_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    activity_code varchar(20) NOT NULL,
    activity_name varchar(255) NOT NULL,
    description text,
    iso_maintenance_reference varchar(50) DEFAULT NULL,
    activity_category VARCHAR(100) NOT NULL CONSTRAINT chk_activity_codes_activity_category CHECK (activity_category IN ('inspection','preventive','corrective','predictive','modification','overhaul')),
    typical_duration_minutes INTEGER DEFAULT NULL,
    required_skills text,
    safety_precautions text,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_activity_codes_activity_code UNIQUE (activity_code)
);

CREATE TABLE IF NOT EXISTS failure_modes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    failure_mode varchar(255) NOT NULL,
    failure_cause varchar(255) DEFAULT NULL,
    failure_mechanism varchar(255) DEFAULT NULL,
    typical_symptoms text,
    recommended_action text,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS equipment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    facility_id INTEGER DEFAULT NULL,
    name varchar(100) NOT NULL,
    code varchar(50) NOT NULL,
    description text,
    category varchar(50) DEFAULT NULL,
    manufacturer varchar(100) DEFAULT NULL,
    model varchar(100) DEFAULT NULL,
    serial_number varchar(100) DEFAULT NULL,
    location varchar(100) DEFAULT NULL,
    install_date date DEFAULT NULL,
    warranty_expiry date DEFAULT NULL,
    status VARCHAR(100) DEFAULT 'operational' CONSTRAINT chk_equipment_status CHECK (status IN ('operational','maintenance','out_of_order','retired')),
    criticality VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_equipment_criticality CHECK (criticality IN ('low','medium','high','critical')),
    equipment_category_id INTEGER DEFAULT NULL,
    equipment_class_id INTEGER DEFAULT NULL,
    equipment_type_id INTEGER DEFAULT NULL,
    subunit_id INTEGER DEFAULT NULL,
    maintainable_item_id INTEGER DEFAULT NULL,
    purchase_cost NUMERIC(12,2) DEFAULT NULL,
    purchase_date date DEFAULT NULL,
    created_by INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    sap_equipment_reference varchar(50) DEFAULT NULL,
    sap_floc_hint varchar(50) DEFAULT NULL,
    qr_token VARCHAR(32) DEFAULT NULL CONSTRAINT uq_equipment_qr_token UNIQUE,
    qr_token_generated_at TIMESTAMPTZ DEFAULT NULL,
    qr_code VARCHAR(100) DEFAULT NULL CONSTRAINT uq_equipment_qr_code UNIQUE,
    PRIMARY KEY (id),
    CONSTRAINT uq_equipment_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS equipment_mapping_change_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    change_type varchar(50) NOT NULL,
    old_value varchar(100) DEFAULT NULL,
    new_value varchar(100) DEFAULT NULL,
    changed_by INTEGER DEFAULT NULL,
    changed_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    change_reason text,
    batch_id varchar(100) DEFAULT NULL,
    PRIMARY KEY (id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_classes_equipment_classes_ibfk_1'
          AND conrelid = 'equipment_classes'::regclass
    ) THEN
        ALTER TABLE equipment_classes
            ADD CONSTRAINT fk_equipment_classes_equipment_classes_ibfk_1
            FOREIGN KEY (category_id)
            REFERENCES equipment_categories(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_types_equipment_types_ibfk_1'
          AND conrelid = 'equipment_types'::regclass
    ) THEN
        ALTER TABLE equipment_types
            ADD CONSTRAINT fk_equipment_types_equipment_types_ibfk_1
            FOREIGN KEY (class_id)
            REFERENCES equipment_classes(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_type_industries_equipment_type_industries_ibfk_1'
          AND conrelid = 'equipment_type_industries'::regclass
    ) THEN
        ALTER TABLE equipment_type_industries
            ADD CONSTRAINT fk_equipment_type_industries_equipment_type_industries_ibfk_1
            FOREIGN KEY (equipment_type_id)
            REFERENCES equipment_types(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_type_industries_equipment_type_industries_ibfk_2'
          AND conrelid = 'equipment_type_industries'::regclass
    ) THEN
        ALTER TABLE equipment_type_industries
            ADD CONSTRAINT fk_equipment_type_industries_equipment_type_industries_ibfk_2
            FOREIGN KEY (industry_id)
            REFERENCES industries(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_subunits_subunits_ibfk_1'
          AND conrelid = 'subunits'::regclass
    ) THEN
        ALTER TABLE subunits
            ADD CONSTRAINT fk_subunits_subunits_ibfk_1
            FOREIGN KEY (equipment_type_id)
            REFERENCES equipment_types(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_subunits_equipment_subunits_ibfk_1'
          AND conrelid = 'equipment_subunits'::regclass
    ) THEN
        ALTER TABLE equipment_subunits
            ADD CONSTRAINT fk_equipment_subunits_equipment_subunits_ibfk_1
            FOREIGN KEY (equipment_type_id)
            REFERENCES equipment_types(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_maintainable_items_maintainable_items_ibfk_1'
          AND conrelid = 'maintainable_items'::regclass
    ) THEN
        ALTER TABLE maintainable_items
            ADD CONSTRAINT fk_maintainable_items_maintainable_items_ibfk_1
            FOREIGN KEY (subunit_id)
            REFERENCES equipment_subunits(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_object_parts_object_parts_ibfk_1'
          AND conrelid = 'object_parts'::regclass
    ) THEN
        ALTER TABLE object_parts
            ADD CONSTRAINT fk_object_parts_object_parts_ibfk_1
            FOREIGN KEY (equipment_class_id)
            REFERENCES equipment_classes(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_damage_codes_damage_codes_ibfk_1'
          AND conrelid = 'damage_codes'::regclass
    ) THEN
        ALTER TABLE damage_codes
            ADD CONSTRAINT fk_damage_codes_damage_codes_ibfk_1
            FOREIGN KEY (equipment_class_id)
            REFERENCES equipment_classes(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_failure_modes_failure_modes_ibfk_1'
          AND conrelid = 'failure_modes'::regclass
    ) THEN
        ALTER TABLE failure_modes
            ADD CONSTRAINT fk_failure_modes_failure_modes_ibfk_1
            FOREIGN KEY (equipment_type_id)
            REFERENCES equipment_types(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_equipment_ibfk_1'
          AND conrelid = 'equipment'::regclass
    ) THEN
        ALTER TABLE equipment
            ADD CONSTRAINT fk_equipment_equipment_ibfk_1
            FOREIGN KEY (facility_id)
            REFERENCES facilities(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_equipment_ibfk_2'
          AND conrelid = 'equipment'::regclass
    ) THEN
        ALTER TABLE equipment
            ADD CONSTRAINT fk_equipment_equipment_ibfk_2
            FOREIGN KEY (created_by)
            REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_fk_equip_category'
          AND conrelid = 'equipment'::regclass
    ) THEN
        ALTER TABLE equipment
            ADD CONSTRAINT fk_equipment_fk_equip_category
            FOREIGN KEY (equipment_category_id)
            REFERENCES equipment_categories(id) ON DELETE SET NULL;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_fk_equip_class'
          AND conrelid = 'equipment'::regclass
    ) THEN
        ALTER TABLE equipment
            ADD CONSTRAINT fk_equipment_fk_equip_class
            FOREIGN KEY (equipment_class_id)
            REFERENCES equipment_classes(id) ON DELETE SET NULL;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_fk_equip_item'
          AND conrelid = 'equipment'::regclass
    ) THEN
        ALTER TABLE equipment
            ADD CONSTRAINT fk_equipment_fk_equip_item
            FOREIGN KEY (maintainable_item_id)
            REFERENCES maintainable_items(id) ON DELETE SET NULL;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_fk_equip_subunit'
          AND conrelid = 'equipment'::regclass
    ) THEN
        ALTER TABLE equipment
            ADD CONSTRAINT fk_equipment_fk_equip_subunit
            FOREIGN KEY (subunit_id)
            REFERENCES subunits(id) ON DELETE SET NULL;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_fk_equip_type'
          AND conrelid = 'equipment'::regclass
    ) THEN
        ALTER TABLE equipment
            ADD CONSTRAINT fk_equipment_fk_equip_type
            FOREIGN KEY (equipment_type_id)
            REFERENCES equipment_types(id) ON DELETE SET NULL;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_equipment_fk_equipment_organization'
          AND conrelid = 'equipment'::regclass
    ) THEN
        ALTER TABLE equipment
            ADD CONSTRAINT fk_equipment_fk_equipment_organization
            FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE CASCADE;
    END IF;
END
$$;
