-- ODM-CMMS PostgreSQL Schema — 003_templates_maintenance.sql
-- Generated from MySQL historical schema reference + repository drift


CREATE TABLE IF NOT EXISTS template_families (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    family_code varchar(50) NOT NULL,
    family_name varchar(100) NOT NULL,
    description text,
    applicable_industries JSONB DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_template_families_family_code UNIQUE (family_code)
);

CREATE TABLE IF NOT EXISTS template_family_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    family_code varchar(50) NOT NULL,
    task_kind varchar(50) NOT NULL,
    frequency_value INTEGER NOT NULL,
    frequency_unit varchar(50) NOT NULL,
    estimated_duration_minutes INTEGER NOT NULL,
    sort_order INTEGER DEFAULT '0',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_template_family_rules_unique_family_task UNIQUE (family_code, task_kind)
);

CREATE TABLE IF NOT EXISTS equipment_type_family_mappings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    family_code varchar(50) NOT NULL,
    mapping_source varchar(50) DEFAULT 'seed',
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_equipment_type_family_mappings_unique_equip_family UNIQUE (equipment_type_id)
);

CREATE TABLE IF NOT EXISTS equipment_type_family_proposals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    proposed_family_code VARCHAR(50) NOT NULL,
    proposal_source VARCHAR(50) NOT NULL,
    proposal_reason TEXT DEFAULT NULL,
    confidence_score NUMERIC(3,2) DEFAULT NULL,
    proposed_by INTEGER DEFAULT NULL,
    proposed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    review_status VARCHAR(20) DEFAULT 'pending',
    reviewed_by INTEGER DEFAULT NULL,
    reviewed_at TIMESTAMPTZ DEFAULT NULL,
    review_notes TEXT DEFAULT NULL,
    applied_at TIMESTAMPTZ DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_equipment_type_family_proposals_uq_unique_equip_proposal UNIQUE (equipment_type_id, proposed_family_code)
);

CREATE TABLE IF NOT EXISTS seed_batches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_id varchar(100) NOT NULL,
    batch_name varchar(255) NOT NULL,
    batch_version varchar(20) NOT NULL,
    entity_type varchar(50) NOT NULL,
    entity_count INTEGER DEFAULT '0',
    metadata JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_seed_batches_batch_id UNIQUE (batch_id)
);

CREATE TABLE IF NOT EXISTS seed_batch_entities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_id varchar(100) NOT NULL,
    entity_type varchar(50) NOT NULL,
    entity_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_seed_batch_entities_unique_batch_entity UNIQUE (batch_id, entity_type, entity_id)
);

CREATE TABLE IF NOT EXISTS task_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER DEFAULT NULL,
    equipment_type_id INTEGER NOT NULL,
    industry_id INTEGER DEFAULT NULL,
    activity_code_id INTEGER DEFAULT NULL,
    template_code varchar(100) DEFAULT NULL,
    template_name varchar(255) NOT NULL,
    maintenance_type varchar(50) NOT NULL,
    task_scope varchar(100) DEFAULT NULL,
    description text,
    frequency_value INTEGER DEFAULT NULL,
    frequency_unit varchar(50) DEFAULT NULL,
    estimated_duration_minutes INTEGER DEFAULT NULL,
    required_skills text,
    required_tools text,
    is_active BOOLEAN DEFAULT TRUE,
    created_by INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    frequency_type VARCHAR(100) DEFAULT NULL CONSTRAINT chk_task_templates_frequency_type CHECK (frequency_type IN ('daily','weekly','monthly')),
    frequency_interval INTEGER DEFAULT '1',
    day_of_week SMALLINT DEFAULT NULL,
    day_of_month SMALLINT DEFAULT NULL,
    start_date date DEFAULT NULL,
    priority VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_task_templates_priority CHECK (priority IN ('low','medium','high','urgent')),
    task_kind varchar(50) DEFAULT NULL,
    is_system BOOLEAN DEFAULT FALSE,
    is_editable BOOLEAN DEFAULT TRUE,
    parent_template_id INTEGER DEFAULT NULL,
    seed_batch_id varchar(100) DEFAULT NULL,
    version INTEGER DEFAULT '1',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS task_template_steps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_id INTEGER NOT NULL,
    step_no INTEGER NOT NULL,
    step_type varchar(50) NOT NULL,
    activity_code_id INTEGER DEFAULT NULL,
    instruction text NOT NULL,
    data_type varchar(50) DEFAULT NULL,
    expected_value text,
    min_value NUMERIC(12,4) DEFAULT NULL,
    max_value NUMERIC(12,4) DEFAULT NULL,
    unit varchar(50) DEFAULT NULL,
    is_required BOOLEAN DEFAULT TRUE,
    options JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    safety_note text,
    is_visual_only BOOLEAN DEFAULT TRUE,
    requires_equipment_stopped BOOLEAN DEFAULT FALSE,
    prohibit_if_running BOOLEAN DEFAULT FALSE,
    prohibit_opening_covers BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS task_template_safety_controls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_id INTEGER NOT NULL,
    safety_type varchar(50) NOT NULL,
    description text NOT NULL,
    is_mandatory BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS task_master (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_code varchar(20) NOT NULL,
    title varchar(200) NOT NULL,
    description text,
    task_type VARCHAR(100) NOT NULL CONSTRAINT chk_task_master_task_type CHECK (task_type IN ('inspection','maintenance','repair','calibration','cleaning','lubrication')),
    estimated_duration INTEGER DEFAULT NULL,
    required_skills text,
    safety_instructions text,
    required_tools text,
    required_parts text,
    is_active BOOLEAN DEFAULT TRUE,
    created_by INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_task_master_task_code UNIQUE (task_code)
);

CREATE TABLE IF NOT EXISTS schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schedule_code varchar(20) NOT NULL,
    equipment_id INTEGER NOT NULL,
    task_master_id INTEGER NOT NULL,
    title varchar(200) NOT NULL,
    description text,
    frequency_type VARCHAR(100) NOT NULL CONSTRAINT chk_schedules_frequency_type CHECK (frequency_type IN ('daily','weekly','monthly','quarterly','yearly','hours_based','custom')),
    frequency_value INTEGER DEFAULT '1',
    frequency_hours INTEGER DEFAULT NULL,
    day_of_week SMALLINT DEFAULT NULL,
    day_of_month SMALLINT DEFAULT NULL,
    month_of_year SMALLINT DEFAULT NULL,
    start_date date NOT NULL,
    end_date date DEFAULT NULL,
    next_due_date date DEFAULT NULL,
    estimated_hours INTEGER DEFAULT NULL,
    assigned_to INTEGER DEFAULT NULL,
    priority VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_schedules_priority CHECK (priority IN ('low','medium','high','urgent')),
    is_active BOOLEAN DEFAULT TRUE,
    created_by INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_schedules_schedule_code UNIQUE (schedule_code)
);

CREATE TABLE IF NOT EXISTS maintenance_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    task_template_id INTEGER NOT NULL,
    equipment_id INTEGER DEFAULT NULL,
    plan_code varchar(50) DEFAULT NULL,
    plan_name varchar(255) NOT NULL,
    description text,
    frequency_type VARCHAR(100) NOT NULL CONSTRAINT chk_maintenance_plans_frequency_type CHECK (frequency_type IN ('daily','weekly','monthly','yearly')),
    frequency_interval INTEGER DEFAULT '1',
    day_of_week SMALLINT DEFAULT NULL,
    day_of_month SMALLINT DEFAULT NULL,
    month_of_year SMALLINT DEFAULT NULL,
    start_date date NOT NULL,
    end_date date DEFAULT NULL,
    priority VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_maintenance_plans_priority CHECK (priority IN ('low','medium','high','urgent')),
    assigned_to INTEGER DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    last_run_date date DEFAULT NULL,
    next_run_date date DEFAULT NULL,
    created_by INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS plan_equipment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    maintenance_plan_id INTEGER NOT NULL,
    equipment_id INTEGER NOT NULL,
    custom_frequency_type VARCHAR(50) DEFAULT NULL CONSTRAINT chk_plan_equip_freq CHECK (custom_frequency_type IN ('daily', 'weekly', 'monthly', 'yearly')),
    custom_frequency_interval INTEGER DEFAULT NULL,
    custom_priority VARCHAR(50) DEFAULT NULL CONSTRAINT chk_plan_equip_prio CHECK (custom_priority IN ('low', 'medium', 'high', 'urgent')),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_plan_equipment_uq_unique_plan_equipment UNIQUE (maintenance_plan_id, equipment_id)
);

CREATE TABLE IF NOT EXISTS smp_families (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    family_code varchar(50) NOT NULL,
    family_name varchar(200) NOT NULL,
    description text,
    is_active BOOLEAN DEFAULT TRUE,
    created_by INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_smp_families_unique_family_code_org UNIQUE (organization_id, family_code)
);

CREATE TABLE IF NOT EXISTS smp_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    family_id INTEGER NOT NULL,
    task_code varchar(50) NOT NULL,
    task_name varchar(200) NOT NULL,
    description text,
    frequency_type VARCHAR(100) NOT NULL CONSTRAINT chk_smp_tasks_frequency_type CHECK (frequency_type IN ('daily','weekly','monthly','quarterly','yearly','hours_based')),
    frequency_value INTEGER DEFAULT '1',
    estimated_duration INTEGER DEFAULT NULL,
    priority VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_smp_tasks_priority CHECK (priority IN ('low','medium','high','urgent')),
    is_active BOOLEAN DEFAULT TRUE,
    created_by INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_smp_tasks_unique_task_code_org UNIQUE (organization_id, task_code)
);

ALTER TABLE template_family_rules ADD CONSTRAINT fk_template_family_rules_template_family_rules_ibfk_1 FOREIGN KEY (family_code) REFERENCES template_families(family_code) ON DELETE CASCADE;
ALTER TABLE equipment_type_family_mappings ADD CONSTRAINT fk_etfm_equip_type_id FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE CASCADE;
ALTER TABLE equipment_type_family_mappings ADD CONSTRAINT fk_etfm_family_code FOREIGN KEY (family_code) REFERENCES template_families(family_code) ON DELETE CASCADE;
ALTER TABLE equipment_type_family_proposals ADD CONSTRAINT fk_equipment_type_family_proposals_fk_equip_proposal_type FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE CASCADE;
ALTER TABLE equipment_type_family_proposals ADD CONSTRAINT fk_equipment_type_family_proposals_fk_equip_proposal_family FOREIGN KEY (proposed_family_code) REFERENCES template_families(family_code) ON DELETE CASCADE;
ALTER TABLE equipment_type_family_proposals ADD CONSTRAINT fk_equipment_type_family_proposals_fk_equip_proposal_by FOREIGN KEY (proposed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE equipment_type_family_proposals ADD CONSTRAINT fk_equipment_type_family_proposals_fk_equip_proposal_rev_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE seed_batch_entities ADD CONSTRAINT fk_seed_batch_entities_seed_batch_entities_ibfk_1 FOREIGN KEY (batch_id) REFERENCES seed_batches(batch_id) ON DELETE CASCADE;
ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_fk_task_template_activity FOREIGN KEY (activity_code_id) REFERENCES activity_codes(id) ON DELETE SET NULL;
ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_fk_task_template_seed_batch FOREIGN KEY (seed_batch_id) REFERENCES seed_batches(batch_id) ON DELETE SET NULL;
ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_task_templates_ibfk_1 FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE CASCADE;
ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_task_templates_ibfk_2 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_task_templates_ibfk_3 FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_fk_task_template_industry_mig FOREIGN KEY (industry_id) REFERENCES industries(id) ON DELETE SET NULL;
ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_fk_task_template_parent_mig FOREIGN KEY (parent_template_id) REFERENCES task_templates(id) ON DELETE SET NULL;
ALTER TABLE task_template_steps ADD CONSTRAINT fk_task_template_steps_fk_step_activity FOREIGN KEY (activity_code_id) REFERENCES activity_codes(id) ON DELETE SET NULL;
ALTER TABLE task_template_steps ADD CONSTRAINT fk_task_template_steps_task_template_steps_ibfk_1 FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE CASCADE;
ALTER TABLE task_template_safety_controls ADD CONSTRAINT fk_task_template_safety_controls_task_template_safety_controls_ibfk_1 FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE CASCADE;
ALTER TABLE task_master ADD CONSTRAINT fk_task_master_fk_task_master_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE task_master ADD CONSTRAINT fk_task_master_task_master_ibfk_1 FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE schedules ADD CONSTRAINT fk_schedules_fk_schedules_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE schedules ADD CONSTRAINT fk_schedules_schedules_ibfk_1 FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE schedules ADD CONSTRAINT fk_schedules_schedules_ibfk_2 FOREIGN KEY (task_master_id) REFERENCES task_master(id) ON DELETE CASCADE;
ALTER TABLE schedules ADD CONSTRAINT fk_schedules_schedules_ibfk_3 FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE schedules ADD CONSTRAINT fk_schedules_schedules_ibfk_4 FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE plan_equipment ADD CONSTRAINT fk_plan_equipment_fk_plan_equipment_plan FOREIGN KEY (maintenance_plan_id) REFERENCES maintenance_plans(id) ON DELETE CASCADE;
ALTER TABLE plan_equipment ADD CONSTRAINT fk_plan_equipment_fk_plan_equipment_equip FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE smp_tasks ADD CONSTRAINT fk_smp_tasks_smp_tasks_ibfk_1 FOREIGN KEY (family_id) REFERENCES smp_families(id) ON DELETE CASCADE;
