-- ODM-CMMS PostgreSQL Schema — 004_work_management.sql
-- Generated from MySQL historical schema reference + repository drift


CREATE TABLE IF NOT EXISTS work_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wo_number varchar(20) NOT NULL,
    schedule_id INTEGER DEFAULT NULL,
    equipment_id INTEGER NOT NULL,
    task_master_id INTEGER DEFAULT NULL,
    title varchar(200) NOT NULL,
    description text,
    wo_type VARCHAR(100) DEFAULT 'corrective' CONSTRAINT chk_work_orders_wo_type CHECK (wo_type IN ('preventive','corrective','predictive','emergency','project')),
    priority VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_work_orders_priority CHECK (priority IN ('low','medium','high','urgent')),
    status VARCHAR(100) DEFAULT 'open' CONSTRAINT chk_work_orders_status CHECK (status IN ('open','assigned','in_progress','on_hold','completed','cancelled','closed')),
    assigned_to INTEGER DEFAULT NULL,
    requested_by INTEGER DEFAULT NULL,
    requested_date TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    scheduled_start TIMESTAMPTZ DEFAULT NULL,
    scheduled_end TIMESTAMPTZ DEFAULT NULL,
    actual_start TIMESTAMPTZ DEFAULT NULL,
    actual_end TIMESTAMPTZ DEFAULT NULL,
    estimated_hours INTEGER DEFAULT NULL,
    actual_hours INTEGER DEFAULT NULL,
    completion_notes text,
    completion_percentage INTEGER DEFAULT '0',
    is_recurring BOOLEAN DEFAULT FALSE,
    parent_wo_id INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    task_template_id INTEGER DEFAULT NULL,
    scheduled_date DATE DEFAULT NULL,
    maintenance_plan_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_work_orders_wo_number UNIQUE (wo_number)
);

CREATE TABLE IF NOT EXISTS work_order_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_order_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    note text NOT NULL,
    note_type VARCHAR(100) DEFAULT 'general' CONSTRAINT chk_work_order_notes_note_type CHECK (note_type IN ('general','update','delay','parts_needed','safety','completion')),
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS work_order_failures (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_order_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    organization_id INTEGER NOT NULL,
    equipment_type_id INTEGER DEFAULT NULL,
    subunit_id INTEGER DEFAULT NULL,
    maintainable_item_id INTEGER DEFAULT NULL,
    object_part_id INTEGER DEFAULT NULL,
    damage_code_id INTEGER DEFAULT NULL,
    cause_code_id INTEGER DEFAULT NULL,
    activity_code_id INTEGER DEFAULT NULL,
    failure_description text,
    failure_mode_text varchar(255) DEFAULT NULL,
    cause_description text,
    action_taken text,
    detected_by_user_id INTEGER DEFAULT NULL,
    detected_at TIMESTAMPTZ NULL DEFAULT NULL,
    detection_method VARCHAR(100) DEFAULT 'operator_report' CONSTRAINT chk_work_order_failures_detection_method CHECK (detection_method IN ('inspection','monitoring','operator_report','breakdown','predictive')),
    severity_level VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_work_order_failures_severity_level CHECK (severity_level IN ('low','medium','high','critical')),
    safety_impact BOOLEAN DEFAULT FALSE,
    environmental_impact BOOLEAN DEFAULT FALSE,
    production_impact_hours NUMERIC(8,2) DEFAULT NULL,
    failure_start_at TIMESTAMPTZ NULL DEFAULT NULL,
    failure_end_at TIMESTAMPTZ NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inspection_points (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_master_id INTEGER NOT NULL,
    point_code varchar(20) NOT NULL,
    description varchar(500) NOT NULL,
    input_type VARCHAR(100) NOT NULL DEFAULT 'numeric' CONSTRAINT chk_inspection_points_input_type CHECK (input_type IN ('numeric','text','boolean','select','multiselect','photo')),
    min_value NUMERIC(10,2) DEFAULT NULL,
    max_value NUMERIC(10,2) DEFAULT NULL,
    unit_of_measure varchar(20) DEFAULT NULL,
    expected_value varchar(255) DEFAULT NULL,
    acceptable_values text,
    is_critical BOOLEAN DEFAULT FALSE,
    sort_order INTEGER DEFAULT '0',
    help_text text,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_inspection_points_unique_point_code UNIQUE (task_master_id, point_code)
);

CREATE TABLE IF NOT EXISTS inspection_readings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_order_id INTEGER NOT NULL,
    inspection_point_id INTEGER NOT NULL,
    equipment_id INTEGER NOT NULL,
    reading_value varchar(255) DEFAULT NULL,
    reading_json JSONB DEFAULT NULL,
    object_part_id INTEGER DEFAULT NULL,
    damage_code_id INTEGER DEFAULT NULL,
    cause_code_id INTEGER DEFAULT NULL,
    reading_numeric NUMERIC(10,2) DEFAULT NULL,
    reading_text text,
    reading_boolean BOOLEAN DEFAULT NULL,
    reading_photo_url varchar(500) DEFAULT NULL,
    is_passing BOOLEAN DEFAULT NULL,
    notes text,
    taken_by INTEGER NOT NULL,
    taken_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    latitude NUMERIC(10,8) DEFAULT NULL,
    longitude NUMERIC(11,8) DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inspection_results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    facility_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    task_template_id INTEGER NOT NULL,
    task_template_step_id INTEGER NOT NULL,
    recorded_value_text text,
    recorded_value_number NUMERIC(12,4) DEFAULT NULL,
    recorded_value_boolean BOOLEAN DEFAULT NULL,
    recorded_value_json JSONB DEFAULT NULL,
    unit varchar(50) DEFAULT NULL,
    remarks text,
    photo_url varchar(500) DEFAULT NULL,
    recorded_by_user_id INTEGER NOT NULL,
    recorded_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS findings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    facility_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    task_template_id INTEGER DEFAULT NULL,
    task_template_step_id INTEGER DEFAULT NULL,
    object_part_id INTEGER DEFAULT NULL,
    damage_code_id INTEGER DEFAULT NULL,
    cause_code_id INTEGER DEFAULT NULL,
    activity_code_id INTEGER DEFAULT NULL,
    finding_description text NOT NULL,
    severity VARCHAR(100) DEFAULT 'medium' CONSTRAINT chk_findings_severity CHECK (severity IN ('low','medium','high','critical')),
    recommendation text,
    requires_sap_notification BOOLEAN DEFAULT FALSE,
    sap_notification_no varchar(20) DEFAULT NULL,
    reported_by_user_id INTEGER NOT NULL,
    reported_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(100) DEFAULT 'open' CONSTRAINT chk_findings_status CHECK (status IN ('open', 'notified', 'in_progress', 'closed', 'cancelled')),
    equipment_function_impact VARCHAR(100) DEFAULT 'unknown' CONSTRAINT chk_findings_impact CHECK (equipment_function_impact IN ('none', 'reduced', 'degraded', 'failed', 'unknown')),
    operating_condition VARCHAR(100) DEFAULT 'normal' CONSTRAINT chk_findings_condition CHECK (operating_condition IN ('normal', 'abnormal', 'emergency', 'startup', 'shutdown')),
    sap_notification_created_at TIMESTAMPTZ DEFAULT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_fk_work_orders_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_work_orders_ibfk_1 FOREIGN KEY (schedule_id) REFERENCES schedules(id) ON DELETE SET NULL;
ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_work_orders_ibfk_2 FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_work_orders_ibfk_3 FOREIGN KEY (task_master_id) REFERENCES task_master(id) ON DELETE SET NULL;
ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_work_orders_ibfk_4 FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_work_orders_ibfk_5 FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_work_orders_ibfk_6 FOREIGN KEY (parent_wo_id) REFERENCES work_orders(id) ON DELETE SET NULL;
ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_fk_wo_task_template_mig FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE SET NULL;
ALTER TABLE work_orders ADD CONSTRAINT fk_work_orders_fk_wo_maintenance_plan_mig FOREIGN KEY (maintenance_plan_id) REFERENCES maintenance_plans(id) ON DELETE SET NULL;
ALTER TABLE work_order_notes ADD CONSTRAINT fk_work_order_notes_fk_work_order_notes_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE work_order_notes ADD CONSTRAINT fk_work_order_notes_work_order_notes_ibfk_1 FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE work_order_notes ADD CONSTRAINT fk_work_order_notes_work_order_notes_ibfk_2 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_1 FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_10 FOREIGN KEY (activity_code_id) REFERENCES activity_codes(id) ON DELETE SET NULL;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_11 FOREIGN KEY (detected_by_user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_2 FOREIGN KEY (asset_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_3 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_4 FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE SET NULL;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_5 FOREIGN KEY (subunit_id) REFERENCES equipment_subunits(id) ON DELETE SET NULL;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_6 FOREIGN KEY (maintainable_item_id) REFERENCES maintainable_items(id) ON DELETE SET NULL;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_7 FOREIGN KEY (object_part_id) REFERENCES object_parts(id) ON DELETE SET NULL;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_8 FOREIGN KEY (damage_code_id) REFERENCES damage_codes(id) ON DELETE SET NULL;
ALTER TABLE work_order_failures ADD CONSTRAINT fk_work_order_failures_work_order_failures_ibfk_9 FOREIGN KEY (cause_code_id) REFERENCES cause_codes(id) ON DELETE SET NULL;
ALTER TABLE inspection_points ADD CONSTRAINT fk_inspection_points_fk_inspection_points_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE inspection_points ADD CONSTRAINT fk_inspection_points_inspection_points_ibfk_1 FOREIGN KEY (task_master_id) REFERENCES task_master(id) ON DELETE CASCADE;
ALTER TABLE inspection_readings ADD CONSTRAINT fk_inspection_readings_fk_inspection_cause FOREIGN KEY (cause_code_id) REFERENCES cause_codes(id) ON DELETE SET NULL;
ALTER TABLE inspection_readings ADD CONSTRAINT fk_inspection_readings_fk_inspection_damage FOREIGN KEY (damage_code_id) REFERENCES damage_codes(id) ON DELETE SET NULL;
ALTER TABLE inspection_readings ADD CONSTRAINT fk_inspection_readings_fk_inspection_object_part FOREIGN KEY (object_part_id) REFERENCES object_parts(id) ON DELETE SET NULL;
ALTER TABLE inspection_readings ADD CONSTRAINT fk_inspection_readings_fk_inspection_readings_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE inspection_readings ADD CONSTRAINT fk_inspection_readings_inspection_readings_ibfk_1 FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE inspection_readings ADD CONSTRAINT fk_inspection_readings_inspection_readings_ibfk_2 FOREIGN KEY (inspection_point_id) REFERENCES inspection_points(id) ON DELETE CASCADE;
ALTER TABLE inspection_readings ADD CONSTRAINT fk_inspection_readings_inspection_readings_ibfk_3 FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE inspection_readings ADD CONSTRAINT fk_inspection_readings_inspection_readings_ibfk_4 FOREIGN KEY (taken_by) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE inspection_results ADD CONSTRAINT fk_inspection_results_inspection_results_ibfk_1 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE inspection_results ADD CONSTRAINT fk_inspection_results_inspection_results_ibfk_2 FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE CASCADE;
ALTER TABLE inspection_results ADD CONSTRAINT fk_inspection_results_inspection_results_ibfk_3 FOREIGN KEY (asset_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE inspection_results ADD CONSTRAINT fk_inspection_results_inspection_results_ibfk_4 FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE CASCADE;
ALTER TABLE inspection_results ADD CONSTRAINT fk_inspection_results_inspection_results_ibfk_5 FOREIGN KEY (task_template_step_id) REFERENCES task_template_steps(id) ON DELETE CASCADE;
ALTER TABLE inspection_results ADD CONSTRAINT fk_inspection_results_inspection_results_ibfk_6 FOREIGN KEY (recorded_by_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_1 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_10 FOREIGN KEY (reported_by_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_2 FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE CASCADE;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_3 FOREIGN KEY (asset_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_4 FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE SET NULL;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_5 FOREIGN KEY (task_template_step_id) REFERENCES task_template_steps(id) ON DELETE SET NULL;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_6 FOREIGN KEY (object_part_id) REFERENCES object_parts(id) ON DELETE SET NULL;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_7 FOREIGN KEY (damage_code_id) REFERENCES damage_codes(id) ON DELETE SET NULL;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_8 FOREIGN KEY (cause_code_id) REFERENCES cause_codes(id) ON DELETE SET NULL;
ALTER TABLE findings ADD CONSTRAINT fk_findings_findings_ibfk_9 FOREIGN KEY (activity_code_id) REFERENCES activity_codes(id) ON DELETE SET NULL;
