-- ODM-CMMS PostgreSQL Schema — 005_commercial_security.sql
-- Generated from MySQL historical schema reference + repository drift


CREATE TABLE IF NOT EXISTS subscription_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plan_code varchar(50) NOT NULL,
    plan_name varchar(100) NOT NULL,
    description text,
    included_users INTEGER NOT NULL DEFAULT '5',
    max_users INTEGER DEFAULT NULL,
    base_price NUMERIC(10,2) NOT NULL DEFAULT '0.00',
    price_per_additional_user NUMERIC(10,2) DEFAULT '0.00',
    features text,
    is_active BOOLEAN DEFAULT TRUE,
    is_public BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT '0',
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    max_facilities INTEGER DEFAULT NULL,
    max_equipment INTEGER DEFAULT NULL,
    max_custom_fields INTEGER DEFAULT NULL,
    max_sso_providers INTEGER DEFAULT '0',
    audit_retention_days INTEGER DEFAULT '30',
    max_api_keys INTEGER DEFAULT '0',
    PRIMARY KEY (id),
    CONSTRAINT uq_subscription_plans_plan_code UNIQUE (plan_code)
);

CREATE TABLE IF NOT EXISTS organization_subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    plan_id INTEGER NOT NULL,
    included_users INTEGER NOT NULL DEFAULT '5',
    extra_users INTEGER DEFAULT '0',
    max_users INTEGER DEFAULT NULL,
    base_price NUMERIC(10,2) NOT NULL DEFAULT '0.00',
    price_per_additional_user NUMERIC(10,2) DEFAULT '0.00',
    status VARCHAR(100) DEFAULT 'trial' CONSTRAINT chk_organization_subscriptions_status CHECK (status IN ('trial','active','past_due','cancelled','suspended')),
    billing_cycle VARCHAR(100) DEFAULT 'monthly' CONSTRAINT chk_organization_subscriptions_billing_cycle CHECK (billing_cycle IN ('monthly','annual')),
    current_period_start date DEFAULT NULL,
    current_period_end date DEFAULT NULL,
    payment_method_id varchar(100) DEFAULT NULL,
    stripe_subscription_id varchar(100) DEFAULT NULL,
    stripe_customer_id varchar(100) DEFAULT NULL,
    cancel_at_period_end BOOLEAN DEFAULT FALSE,
    cancelled_at TIMESTAMPTZ NULL DEFAULT NULL,
    cancellation_reason text,
    seats_used INTEGER DEFAULT '0',
    seats_available INTEGER DEFAULT '0',
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    max_facilities INTEGER DEFAULT NULL,
    max_equipment INTEGER DEFAULT NULL,
    stripe_price_id varchar(100) DEFAULT NULL,
    max_custom_fields INTEGER DEFAULT NULL,
    max_sso_providers INTEGER DEFAULT '0',
    audit_retention_days INTEGER DEFAULT '30',
    max_api_keys INTEGER DEFAULT '0',
    PRIMARY KEY (id),
    CONSTRAINT uq_organization_subscriptions_organization_id UNIQUE (organization_id)
);

CREATE TABLE IF NOT EXISTS stripe_customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    stripe_customer_id varchar(100) NOT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_stripe_customers_organization_id UNIQUE (organization_id)
);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    stripe_payment_intent_id varchar(100) DEFAULT NULL,
    stripe_invoice_id varchar(100) DEFAULT NULL,
    amount NUMERIC(10,2) NOT NULL,
    currency varchar(3) DEFAULT 'USD',
    status VARCHAR(100) DEFAULT 'pending' CONSTRAINT chk_payments_status CHECK (status IN ('pending','completed','failed','refunded')),
    type VARCHAR(100) DEFAULT 'subscription' CONSTRAINT chk_payments_type CHECK (type IN ('subscription','extra_seats','one_time')),
    description text,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS api_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    name varchar(100) NOT NULL,
    api_key_hash varchar(255) NOT NULL,
    api_key_prefix varchar(8) NOT NULL,
    scopes JSONB DEFAULT NULL,
    rate_limit_per_minute INTEGER DEFAULT '60',
    last_used_at TIMESTAMPTZ NULL DEFAULT NULL,
    usage_count INTEGER DEFAULT '0',
    expires_at TIMESTAMPTZ NULL DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS api_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    api_key_id INTEGER DEFAULT NULL,
    user_id INTEGER DEFAULT NULL,
    endpoint varchar(500) NOT NULL,
    http_method varchar(10) NOT NULL,
    ip_address varchar(45) DEFAULT NULL,
    user_agent text,
    response_status INTEGER DEFAULT NULL,
    response_time_ms INTEGER DEFAULT NULL,
    error_message text,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS api_rate_limit_tracking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_key_id INTEGER NOT NULL,
    window_start TIMESTAMPTZ NOT NULL,
    request_count INTEGER DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS audit_configurations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    log_logins BOOLEAN DEFAULT TRUE,
    log_data_exports BOOLEAN DEFAULT TRUE,
    log_user_changes BOOLEAN DEFAULT TRUE,
    log_work_order_changes BOOLEAN DEFAULT TRUE,
    log_equipment_changes BOOLEAN DEFAULT TRUE,
    log_schedule_changes BOOLEAN DEFAULT TRUE,
    log_settings_changes BOOLEAN DEFAULT TRUE,
    log_level VARCHAR(100) DEFAULT 'standard' CONSTRAINT chk_audit_configurations_log_level CHECK (log_level IN ('minimal','standard','verbose')),
    mask_sensitive_data BOOLEAN DEFAULT TRUE,
    sensitive_fields JSONB DEFAULT NULL,
    alert_on_failed_logins BOOLEAN DEFAULT TRUE,
    alert_on_data_export BOOLEAN DEFAULT TRUE,
    alert_on_admin_actions BOOLEAN DEFAULT TRUE,
    alert_email varchar(200) DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_audit_configurations_organization_id UNIQUE (organization_id)
);

CREATE TABLE IF NOT EXISTS audit_retention_policies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    retention_days INTEGER NOT NULL DEFAULT '365',
    archive_before_delete BOOLEAN DEFAULT FALSE,
    archive_location varchar(500) DEFAULT NULL,
    last_purge_at TIMESTAMPTZ NULL DEFAULT NULL,
    last_purge_count INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_audit_retention_policies_organization_id UNIQUE (organization_id)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER DEFAULT NULL,
    action varchar(50) NOT NULL,
    entity_type varchar(50) NOT NULL,
    entity_id INTEGER DEFAULT NULL,
    old_values JSONB DEFAULT NULL,
    new_values JSONB DEFAULT NULL,
    ip_address varchar(45) DEFAULT NULL,
    user_agent text,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    action varchar(50) NOT NULL,
    entity_type varchar(50) NOT NULL,
    entity_id INTEGER DEFAULT NULL,
    entity_name varchar(200) DEFAULT NULL,
    user_id INTEGER DEFAULT NULL,
    user_name varchar(100) DEFAULT NULL,
    user_role varchar(20) DEFAULT NULL,
    impersonated_by INTEGER DEFAULT NULL,
    old_values JSONB DEFAULT NULL,
    new_values JSONB DEFAULT NULL,
    changed_fields JSONB DEFAULT NULL,
    ip_address varchar(45) DEFAULT NULL,
    user_agent text,
    session_id varchar(200) DEFAULT NULL,
    request_id varchar(100) DEFAULT NULL,
    api_endpoint varchar(500) DEFAULT NULL,
    http_method varchar(10) DEFAULT NULL,
    export_format varchar(20) DEFAULT NULL,
    export_record_count INTEGER DEFAULT NULL,
    login_method varchar(20) DEFAULT NULL,
    sso_provider varchar(50) DEFAULT NULL,
    mfa_used BOOLEAN DEFAULT NULL,
    login_success BOOLEAN DEFAULT NULL,
    failure_reason varchar(200) DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS audit_logs_archive (
    id BIGINT NOT NULL,
    organization_id INTEGER NOT NULL,
    action varchar(50) NOT NULL,
    entity_type varchar(50) NOT NULL,
    entity_id INTEGER DEFAULT NULL,
    entity_name varchar(200) DEFAULT NULL,
    user_id INTEGER DEFAULT NULL,
    user_name varchar(100) DEFAULT NULL,
    old_values JSONB DEFAULT NULL,
    new_values JSONB DEFAULT NULL,
    changed_fields JSONB DEFAULT NULL,
    ip_address varchar(45) DEFAULT NULL,
    user_agent text,
    created_at TIMESTAMPTZ NOT NULL,
    archived_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_organization_subscriptions_organization_subscriptions_ibfk_1'
          AND conrelid = 'organization_subscriptions'::regclass
    ) THEN
        ALTER TABLE organization_subscriptions
            ADD CONSTRAINT fk_organization_subscriptions_organization_subscriptions_ibfk_1
            FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_organization_subscriptions_organization_subscriptions_ibfk_2'
          AND conrelid = 'organization_subscriptions'::regclass
    ) THEN
        ALTER TABLE organization_subscriptions
            ADD CONSTRAINT fk_organization_subscriptions_organization_subscriptions_ibfk_2
            FOREIGN KEY (plan_id)
            REFERENCES subscription_plans(id);
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_stripe_customers_stripe_customers_ibfk_1'
          AND conrelid = 'stripe_customers'::regclass
    ) THEN
        ALTER TABLE stripe_customers
            ADD CONSTRAINT fk_stripe_customers_stripe_customers_ibfk_1
            FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_payments_payments_ibfk_1'
          AND conrelid = 'payments'::regclass
    ) THEN
        ALTER TABLE payments
            ADD CONSTRAINT fk_payments_payments_ibfk_1
            FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_api_keys_api_keys_ibfk_1'
          AND conrelid = 'api_keys'::regclass
    ) THEN
        ALTER TABLE api_keys
            ADD CONSTRAINT fk_api_keys_api_keys_ibfk_1
            FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_api_keys_api_keys_ibfk_2'
          AND conrelid = 'api_keys'::regclass
    ) THEN
        ALTER TABLE api_keys
            ADD CONSTRAINT fk_api_keys_api_keys_ibfk_2
            FOREIGN KEY (user_id)
            REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_api_rate_limit_tracking_fk_api_rate_limit_api_key'
          AND conrelid = 'api_rate_limit_tracking'::regclass
    ) THEN
        ALTER TABLE api_rate_limit_tracking
            ADD CONSTRAINT fk_api_rate_limit_tracking_fk_api_rate_limit_api_key
            FOREIGN KEY (api_key_id)
            REFERENCES api_keys(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_audit_configurations_audit_configurations_ibfk_1'
          AND conrelid = 'audit_configurations'::regclass
    ) THEN
        ALTER TABLE audit_configurations
            ADD CONSTRAINT fk_audit_configurations_audit_configurations_ibfk_1
            FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_audit_retention_policies_audit_retention_policies_ibfk_1'
          AND conrelid = 'audit_retention_policies'::regclass
    ) THEN
        ALTER TABLE audit_retention_policies
            ADD CONSTRAINT fk_audit_retention_policies_audit_retention_policies_ibfk_1
            FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE CASCADE;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_audit_log_audit_log_ibfk_1'
          AND conrelid = 'audit_log'::regclass
    ) THEN
        ALTER TABLE audit_log
            ADD CONSTRAINT fk_audit_log_audit_log_ibfk_1
            FOREIGN KEY (user_id)
            REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_audit_log_fk_audit_log_organization'
          AND conrelid = 'audit_log'::regclass
    ) THEN
        ALTER TABLE audit_log
            ADD CONSTRAINT fk_audit_log_fk_audit_log_organization
            FOREIGN KEY (organization_id)
            REFERENCES organizations(id) ON DELETE CASCADE;
    END IF;
END
$$;
