-- ODM-CMMS PostgreSQL Schema — 006_customization_files.sql
-- Generated from MySQL historical schema reference + repository drift


CREATE TABLE IF NOT EXISTS custom_field_definitions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    entity_type varchar(50) NOT NULL,
    field_name varchar(100) NOT NULL,
    field_label varchar(200) NOT NULL,
    field_type VARCHAR(100) NOT NULL DEFAULT 'text' CONSTRAINT chk_custom_field_definitions_field_type CHECK (field_type IN ('text','number','date','datetime','select','multiselect','checkbox','url','email')),
    field_options JSONB DEFAULT NULL,
    is_required BOOLEAN DEFAULT FALSE,
    default_value text,
    validation_regex varchar(500) DEFAULT NULL,
    placeholder varchar(200) DEFAULT NULL,
    help_text varchar(500) DEFAULT NULL,
    sort_order INTEGER DEFAULT '0',
    is_active BOOLEAN DEFAULT TRUE,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_custom_field_definitions_uk_org_entity_field UNIQUE (organization_id, entity_type, field_name)
);

CREATE TABLE IF NOT EXISTS custom_field_values (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    field_definition_id INTEGER NOT NULL,
    entity_id INTEGER NOT NULL,
    entity_type varchar(50) NOT NULL,
    value_text text,
    value_number NUMERIC(18,4) DEFAULT NULL,
    value_date date DEFAULT NULL,
    value_datetime TIMESTAMPTZ DEFAULT NULL,
    value_json JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_custom_field_values_uk_field_entity UNIQUE (field_definition_id, entity_id)
);

CREATE TABLE IF NOT EXISTS custom_field_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    field_definition_id INTEGER NOT NULL,
    action varchar(20) NOT NULL,
    old_value JSONB DEFAULT NULL,
    new_value JSONB DEFAULT NULL,
    changed_by INTEGER NOT NULL,
    changed_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entity_type VARCHAR(100) NOT NULL CONSTRAINT chk_attachments_entity_type CHECK (entity_type IN ('work_order','equipment','task_master','inspection_reading')),
    entity_id INTEGER NOT NULL,
    file_name varchar(255) NOT NULL,
    original_name varchar(255) NOT NULL,
    file_path varchar(500) NOT NULL,
    file_size INTEGER DEFAULT NULL,
    mime_type varchar(100) DEFAULT NULL,
    uploaded_by INTEGER DEFAULT NULL,
    uploaded_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS uploaded_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    file_name varchar(255) NOT NULL,
    original_name varchar(255) NOT NULL,
    file_path varchar(500) NOT NULL,
    file_size INTEGER DEFAULT NULL,
    mime_type varchar(100) DEFAULT NULL,
    entity_type varchar(50) DEFAULT NULL,
    entity_id INTEGER DEFAULT NULL,
    uploaded_by INTEGER DEFAULT NULL,
    uploaded_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS asset_template_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asset_id INTEGER NOT NULL,
    template_id INTEGER NOT NULL,
    inherited_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    inherited_from VARCHAR(50) DEFAULT 'equipment_type' CONSTRAINT chk_asset_template_links_inherited_from CHECK (inherited_from IN ('equipment_type', 'manual', 'bulk_import')),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_asset_template_links_uq_unique_asset_template UNIQUE (asset_id, template_id)
);

CREATE TABLE IF NOT EXISTS asset_import_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    imported_by INTEGER DEFAULT NULL,
    filename VARCHAR(255) DEFAULT NULL,
    total_rows INTEGER DEFAULT 0,
    success_count INTEGER DEFAULT 0,
    failed_count INTEGER DEFAULT 0,
    facilities_created INTEGER DEFAULT 0,
    assets_created INTEGER DEFAULT 0,
    errors_json JSONB DEFAULT NULL,
    started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ DEFAULT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE custom_field_definitions ADD CONSTRAINT fk_custom_field_definitions_custom_field_definitions_ibfk_1 FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE custom_field_definitions ADD CONSTRAINT fk_custom_field_definitions_custom_field_definitions_ibfk_2 FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE custom_field_values ADD CONSTRAINT fk_custom_field_values_custom_field_values_ibfk_1 FOREIGN KEY (field_definition_id) REFERENCES custom_field_definitions(id) ON DELETE CASCADE;
ALTER TABLE custom_field_history ADD CONSTRAINT fk_custom_field_history_custom_field_history_ibfk_1 FOREIGN KEY (field_definition_id) REFERENCES custom_field_definitions(id);
ALTER TABLE custom_field_history ADD CONSTRAINT fk_custom_field_history_custom_field_history_ibfk_2 FOREIGN KEY (changed_by) REFERENCES users(id);
ALTER TABLE attachments ADD CONSTRAINT fk_attachments_attachments_ibfk_1 FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE attachments ADD CONSTRAINT fk_attachments_fk_attachments_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE asset_template_links ADD CONSTRAINT fk_asset_template_links_fk_asset_template_links_asset FOREIGN KEY (asset_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE asset_template_links ADD CONSTRAINT fk_asset_template_links_fk_asset_template_links_template FOREIGN KEY (template_id) REFERENCES task_templates(id) ON DELETE CASCADE;
ALTER TABLE asset_import_logs ADD CONSTRAINT fk_asset_import_logs_fk_asset_import_logs_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE asset_import_logs ADD CONSTRAINT fk_asset_import_logs_fk_asset_import_logs_user FOREIGN KEY (imported_by) REFERENCES users(id) ON DELETE SET NULL;
