-- Atiman Knowledge Versioning Foundation
-- Implements the first slice of ATM-013D2:
--   knowledge_packs, knowledge_pack_versions,
--   task_template_versions, task_template_step_versions.
--
-- Principles:
-- - Published versions are immutable.
-- - A task_template_version owns its complete ordered task_template_step_versions.
-- - Existing task_templates/task_template_steps remain untouched; this file only
--   creates the versioning tables that will later receive published versions.
-- - Idempotent deployment: CREATE IF NOT EXISTS throughout.

-- Stable identity for a knowledge pack.
CREATE TABLE IF NOT EXISTS knowledge_packs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pack_code VARCHAR(100) NOT NULL,
    pack_name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_knowledge_packs_pack_code UNIQUE (pack_code)
);

-- Immutable published version of a knowledge pack.
CREATE TABLE IF NOT EXISTS knowledge_pack_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    knowledge_pack_id INTEGER NOT NULL,
    version_number VARCHAR(50) NOT NULL,
    lifecycle_state VARCHAR(50) NOT NULL DEFAULT 'draft'
        CONSTRAINT chk_knowledge_pack_versions_lifecycle_state
        CHECK (lifecycle_state IN ('draft','under_review','approved','published','superseded','retired')),
    effective_from TIMESTAMPTZ NULL,
    effective_until TIMESTAMPTZ NULL,
    superseded_by_version_id INTEGER DEFAULT NULL,
    author_user_id INTEGER DEFAULT NULL,
    reviewer_user_id INTEGER DEFAULT NULL,
    approver_user_id INTEGER DEFAULT NULL,
    reviewed_at TIMESTAMPTZ NULL,
    approved_at TIMESTAMPTZ NULL,
    published_at TIMESTAMPTZ NULL,
    next_review_at TIMESTAMPTZ NULL,
    change_summary TEXT,
    ai_assisted BOOLEAN DEFAULT FALSE,
    ai_assistance_detail JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_knowledge_pack_versions_pack_version UNIQUE (knowledge_pack_id, version_number),
    CONSTRAINT fk_knowledge_pack_versions_knowledge_pack
        FOREIGN KEY (knowledge_pack_id) REFERENCES knowledge_packs(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_pack_versions_superseded_by
        FOREIGN KEY (superseded_by_version_id) REFERENCES knowledge_pack_versions(id) ON DELETE SET NULL
);

-- Immutable published version of a task template.
-- A working task_template record may produce many versions, each frozen at publish time.
CREATE TABLE IF NOT EXISTS task_template_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_id INTEGER NOT NULL,
    version_number INTEGER NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    industry_id INTEGER DEFAULT NULL,
    activity_code_id INTEGER DEFAULT NULL,
    template_code VARCHAR(100) DEFAULT NULL,
    template_name VARCHAR(255) NOT NULL,
    maintenance_type VARCHAR(50) NOT NULL,
    task_scope VARCHAR(100) DEFAULT NULL,
    description TEXT,
    frequency_value INTEGER DEFAULT NULL,
    frequency_unit VARCHAR(50) DEFAULT NULL,
    estimated_duration_minutes INTEGER DEFAULT NULL,
    required_skills TEXT,
    required_tools TEXT,
    priority VARCHAR(100) DEFAULT 'medium',
    task_kind VARCHAR(50) DEFAULT NULL,
    is_system BOOLEAN DEFAULT FALSE,
    is_editable BOOLEAN DEFAULT TRUE,
    parent_template_id INTEGER DEFAULT NULL,
    lifecycle_state_at_publish VARCHAR(50) NOT NULL DEFAULT 'published'
        CONSTRAINT chk_task_template_versions_lifecycle_state
        CHECK (lifecycle_state_at_publish IN ('draft','under_review','approved','published','superseded','retired')),
    published_by_user_id INTEGER DEFAULT NULL,
    published_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    superseded_by_version_id INTEGER DEFAULT NULL,
    knowledge_pack_version_id INTEGER NOT NULL,
    change_rationale TEXT,
    ai_assisted BOOLEAN DEFAULT FALSE,
    ai_assistance_detail JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_task_template_versions_template_version UNIQUE (task_template_id, version_number),
    CONSTRAINT fk_task_template_versions_task_template
        FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_template_versions_equipment_type
        FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_template_versions_industry
        FOREIGN KEY (industry_id) REFERENCES industries(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_activity_code
        FOREIGN KEY (activity_code_id) REFERENCES activity_codes(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_parent_template
        FOREIGN KEY (parent_template_id) REFERENCES task_templates(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_published_by
        FOREIGN KEY (published_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_superseded_by
        FOREIGN KEY (superseded_by_version_id) REFERENCES task_template_versions(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_knowledge_pack_version
        FOREIGN KEY (knowledge_pack_version_id) REFERENCES knowledge_pack_versions(id) ON DELETE RESTRICT
);

-- Immutable published step belonging to a task_template_version.
-- Step versions are not independently versioned; they are published together with
-- their parent template version, forming the atomic publication boundary.
CREATE TABLE IF NOT EXISTS task_template_step_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_version_id INTEGER NOT NULL,
    step_no INTEGER NOT NULL,
    task_template_step_id INTEGER NOT NULL,
    step_type VARCHAR(50) NOT NULL,
    activity_code_id INTEGER DEFAULT NULL,
    instruction TEXT NOT NULL,
    data_type VARCHAR(50) DEFAULT NULL,
    expected_value TEXT,
    min_value NUMERIC(12,4) DEFAULT NULL,
    max_value NUMERIC(12,4) DEFAULT NULL,
    unit VARCHAR(50) DEFAULT NULL,
    is_required BOOLEAN DEFAULT TRUE,
    options JSONB DEFAULT NULL,
    safety_note TEXT,
    is_visual_only BOOLEAN DEFAULT TRUE,
    requires_equipment_stopped BOOLEAN DEFAULT FALSE,
    prohibit_if_running BOOLEAN DEFAULT FALSE,
    prohibit_opening_covers BOOLEAN DEFAULT FALSE,
    ai_assisted BOOLEAN DEFAULT FALSE,
    ai_assistance_detail JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_task_template_step_versions_version_step_no UNIQUE (task_template_version_id, step_no),
    CONSTRAINT fk_task_template_step_versions_template_version
        FOREIGN KEY (task_template_version_id) REFERENCES task_template_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_template_step_versions_task_template_step
        FOREIGN KEY (task_template_step_id) REFERENCES task_template_steps(id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_template_step_versions_activity_code
        FOREIGN KEY (activity_code_id) REFERENCES activity_codes(id) ON DELETE SET NULL
);

-- Membership of a knowledge pack version.
-- Tracks which immutable template/step versions (and later other knowledge entity versions)
-- belong to a published pack version.
CREATE TABLE IF NOT EXISTS knowledge_pack_version_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    knowledge_pack_version_id INTEGER NOT NULL,
    item_type VARCHAR(50) NOT NULL
        CONSTRAINT chk_knowledge_pack_version_items_item_type
        CHECK (item_type IN (
            'task_template_version',
            'task_template_step_version',
            'equipment_category',
            'equipment_class',
            'equipment_type',
            'activity_code',
            'cause_code',
            'damage_code',
            'failure_mode',
            'object_part',
            'maintainable_item',
            'subunit',
            'safety_control',
            'acceptance_criterion'
        )),
    item_version_id INTEGER NOT NULL,
    added_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    added_by_user_id INTEGER DEFAULT NULL,
    change_type VARCHAR(20) NOT NULL DEFAULT 'added'
        CONSTRAINT chk_knowledge_pack_version_items_change_type
        CHECK (change_type IN ('added','updated','removed')),
    PRIMARY KEY (id),
    CONSTRAINT uq_knowledge_pack_version_items_unique UNIQUE (knowledge_pack_version_id, item_type, item_version_id),
    CONSTRAINT fk_knowledge_pack_version_items_pack_version
        FOREIGN KEY (knowledge_pack_version_id) REFERENCES knowledge_pack_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_pack_version_items_added_by
        FOREIGN KEY (added_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);
