-- Atiman Knowledge Versioning Foundation
-- Implements the first slice of ATM-013D2:
--   knowledge_packs, knowledge_pack_versions,
--   task_template_versions, task_template_step_versions.
--
-- Principles:
-- - Published versions are immutable.
-- - A task_template_version owns its complete ordered task_template_step_versions.
-- - Existing task_templates/task_template_steps remain untouched; this file only
--   creates the versioning tables that will later receive published versions.
-- - Idempotent deployment: CREATE IF NOT EXISTS / DROP IF NOT EXISTS throughout.

-- Stable identity for a knowledge pack.
CREATE TABLE IF NOT EXISTS knowledge_packs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pack_code VARCHAR(100) NOT NULL,
    pack_name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_knowledge_packs_pack_code UNIQUE (pack_code)
);

-- Immutable published version of a knowledge pack.
CREATE TABLE IF NOT EXISTS knowledge_pack_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    knowledge_pack_id INTEGER NOT NULL,
    version_number VARCHAR(50) NOT NULL,
    lifecycle_state VARCHAR(50) NOT NULL DEFAULT 'draft'
        CONSTRAINT chk_knowledge_pack_versions_lifecycle_state
        CHECK (lifecycle_state IN ('draft','under_review','approved','published','superseded','retired')),
    effective_from TIMESTAMPTZ NULL,
    effective_until TIMESTAMPTZ NULL,
    superseded_by_version_id INTEGER DEFAULT NULL,
    author_user_id INTEGER DEFAULT NULL,
    reviewer_user_id INTEGER DEFAULT NULL,
    approver_user_id INTEGER DEFAULT NULL,
    reviewed_at TIMESTAMPTZ NULL,
    approved_at TIMESTAMPTZ NULL,
    published_at TIMESTAMPTZ NULL,
    next_review_at TIMESTAMPTZ NULL,
    change_summary TEXT,
    ai_assisted BOOLEAN DEFAULT FALSE,
    ai_assistance_detail JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_knowledge_pack_versions_pack_version UNIQUE (knowledge_pack_id, version_number),
    CONSTRAINT fk_knowledge_pack_versions_knowledge_pack
        FOREIGN KEY (knowledge_pack_id) REFERENCES knowledge_packs(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_pack_versions_superseded_by
        FOREIGN KEY (superseded_by_version_id) REFERENCES knowledge_pack_versions(id) ON DELETE SET NULL
);

-- Immutable published version of a task template.
-- A working task_template record may produce many versions, each frozen at publish time.
-- Task template versions are publication records: their state is published, superseded, or retired.
CREATE TABLE IF NOT EXISTS task_template_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_id INTEGER NOT NULL,
    version_number INTEGER NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    industry_id INTEGER DEFAULT NULL,
    activity_code_id INTEGER DEFAULT NULL,
    template_code VARCHAR(100) DEFAULT NULL,
    template_name VARCHAR(255) NOT NULL,
    maintenance_type VARCHAR(50) NOT NULL,
    task_scope VARCHAR(100) DEFAULT NULL,
    description TEXT,
    frequency_value INTEGER DEFAULT NULL,
    frequency_unit VARCHAR(50) DEFAULT NULL,
    estimated_duration_minutes INTEGER DEFAULT NULL,
    required_skills TEXT,
    required_tools TEXT,
    priority VARCHAR(100) DEFAULT 'medium',
    task_kind VARCHAR(50) DEFAULT NULL,
    is_system BOOLEAN DEFAULT FALSE,
    is_editable BOOLEAN DEFAULT TRUE,
    parent_template_id INTEGER DEFAULT NULL,
    lifecycle_state_at_publish VARCHAR(50) NOT NULL DEFAULT 'published'
        CONSTRAINT chk_task_template_versions_lifecycle_state
        CHECK (lifecycle_state_at_publish IN ('published','superseded','retired')),
    is_step_set_sealed BOOLEAN NOT NULL DEFAULT FALSE,
    published_by_user_id INTEGER DEFAULT NULL,
    published_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    superseded_by_version_id INTEGER DEFAULT NULL,
    change_rationale TEXT,
    ai_assisted BOOLEAN DEFAULT FALSE,
    ai_assistance_detail JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_task_template_versions_template_version UNIQUE (task_template_id, version_number),
    CONSTRAINT fk_task_template_versions_task_template
        FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_template_versions_equipment_type
        FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_template_versions_industry
        FOREIGN KEY (industry_id) REFERENCES industries(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_activity_code
        FOREIGN KEY (activity_code_id) REFERENCES activity_codes(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_parent_template
        FOREIGN KEY (parent_template_id) REFERENCES task_templates(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_published_by
        FOREIGN KEY (published_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_template_versions_superseded_by
        FOREIGN KEY (superseded_by_version_id) REFERENCES task_template_versions(id) ON DELETE SET NULL
);

-- Converge the check constraint on reruns so the allowed states stay in sync
-- with the approved ATM-013E model (published/superseded/retired only).
ALTER TABLE task_template_versions
    DROP CONSTRAINT IF EXISTS chk_task_template_versions_lifecycle_state;
ALTER TABLE task_template_versions
    ADD CONSTRAINT chk_task_template_versions_lifecycle_state
    CHECK (lifecycle_state_at_publish IN ('published','superseded','retired'));

-- Converge the step-set seal column on reruns.
ALTER TABLE task_template_versions
    ADD COLUMN IF NOT EXISTS is_step_set_sealed BOOLEAN NOT NULL DEFAULT FALSE;

-- Deferred seal check: every committed task_template_version must be sealed.
-- This applies to all post-publication states (published, superseded, retired).
-- It permits the assembly pattern (create version, insert ordered steps,
-- update is_step_set_sealed = TRUE) inside a single transaction while
-- guaranteeing the version cannot be committed while still unsealed.
-- Implemented as a deferred constraint trigger because PostgreSQL CHECK
-- constraints cannot be deferred.
CREATE OR REPLACE FUNCTION task_template_version_seal_constraint()
RETURNS TRIGGER AS $$
DECLARE
    current_lifecycle TEXT;
    current_sealed BOOLEAN;
BEGIN
    -- Re-read the current row state so deferred checks see the final
    -- state after all changes in the transaction (e.g., assembly + seal).
    SELECT lifecycle_state_at_publish, is_step_set_sealed
    INTO current_lifecycle, current_sealed
    FROM task_template_versions
    WHERE id = NEW.id;

    IF current_lifecycle IN ('published', 'superseded', 'retired') AND current_sealed = FALSE THEN
        RAISE EXCEPTION 'task_template_version % must be sealed before commit; set is_step_set_sealed = TRUE after adding steps', NEW.id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_task_template_versions_published_seal_constraint
    ON task_template_versions;
DROP TRIGGER IF EXISTS trg_task_template_versions_seal_constraint
    ON task_template_versions;

CREATE CONSTRAINT TRIGGER trg_task_template_versions_seal_constraint
    AFTER INSERT OR UPDATE ON task_template_versions
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION task_template_version_seal_constraint();


-- Immutable published step belonging to a task_template_version.
-- Step versions are not independently versioned; they are published together with
-- their parent template version, forming the atomic publication boundary.
CREATE TABLE IF NOT EXISTS task_template_step_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_version_id INTEGER NOT NULL,
    step_no INTEGER NOT NULL,
    task_template_step_id INTEGER NOT NULL,
    step_type VARCHAR(50) NOT NULL,
    activity_code_id INTEGER DEFAULT NULL,
    instruction TEXT NOT NULL,
    data_type VARCHAR(50) DEFAULT NULL,
    expected_value TEXT,
    min_value NUMERIC(12,4) DEFAULT NULL,
    max_value NUMERIC(12,4) DEFAULT NULL,
    unit VARCHAR(50) DEFAULT NULL,
    is_required BOOLEAN DEFAULT TRUE,
    options JSONB DEFAULT NULL,
    safety_note TEXT,
    is_visual_only BOOLEAN DEFAULT TRUE,
    requires_equipment_stopped BOOLEAN DEFAULT FALSE,
    prohibit_if_running BOOLEAN DEFAULT FALSE,
    prohibit_opening_covers BOOLEAN DEFAULT FALSE,
    ai_assisted BOOLEAN DEFAULT FALSE,
    ai_assistance_detail JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_task_template_step_versions_version_step_no UNIQUE (task_template_version_id, step_no),
    CONSTRAINT fk_task_template_step_versions_template_version
        FOREIGN KEY (task_template_version_id) REFERENCES task_template_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_template_step_versions_task_template_step
        FOREIGN KEY (task_template_step_id) REFERENCES task_template_steps(id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_template_step_versions_activity_code
        FOREIGN KEY (activity_code_id) REFERENCES activity_codes(id) ON DELETE SET NULL
);

-- ============================================================
-- Valid supersession rules
-- ============================================================

-- Supersession is coherent: superseded requires a non-null successor, assigning a
-- successor transitions the current row to superseded, and both rows must belong
-- to the same logical pack. Retirement may have no successor.
CREATE OR REPLACE FUNCTION valid_pack_version_supersession_check()
RETURNS TRIGGER AS $$
DECLARE
    successor_pack_id INTEGER;
    successor_lifecycle TEXT;
    next_id INTEGER;
    visited INTEGER[];
BEGIN
    -- Coerce lifecycle when a successor is assigned.
    IF NEW.superseded_by_version_id IS NOT NULL THEN
        NEW.lifecycle_state := 'superseded';
    END IF;

    -- Superseded must have a successor.
    IF NEW.lifecycle_state = 'superseded' AND NEW.superseded_by_version_id IS NULL THEN
        RAISE EXCEPTION 'superseded knowledge_pack_versions must specify superseded_by_version_id'
            USING ERRCODE = 'check_violation';
    END IF;

    IF NEW.superseded_by_version_id IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.id = NEW.superseded_by_version_id THEN
        RAISE EXCEPTION 'knowledge_pack_versions cannot supersede itself'
            USING ERRCODE = 'check_violation';
    END IF;

    SELECT knowledge_pack_id, lifecycle_state
    INTO successor_pack_id, successor_lifecycle
    FROM knowledge_pack_versions
    WHERE id = NEW.superseded_by_version_id;

    IF successor_pack_id IS NULL THEN
        RAISE EXCEPTION 'superseded_by_version_id must reference an existing knowledge_pack_versions row'
            USING ERRCODE = 'foreign_key_violation';
    END IF;

    IF successor_pack_id IS DISTINCT FROM NEW.knowledge_pack_id THEN
        RAISE EXCEPTION 'superseded_by_version_id must belong to the same knowledge_pack (%)', NEW.knowledge_pack_id
            USING ERRCODE = 'check_violation';
    END IF;

    -- A new successor must currently be published.
    IF successor_lifecycle <> 'published' THEN
        RAISE EXCEPTION 'successor knowledge_pack_versions must be published, not %', successor_lifecycle
            USING ERRCODE = 'check_violation';
    END IF;

    -- Cycle detection: follow the successor chain from the proposed successor.
    -- If it leads back to the current row, the assignment would create a cycle.
    next_id := NEW.superseded_by_version_id;
    visited := ARRAY[NEW.id];
    LOOP
        IF next_id = ANY(visited) THEN
            RAISE EXCEPTION 'supersession assignment would create a cycle involving knowledge_pack_versions %', NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
        visited := array_append(visited, next_id);
        SELECT superseded_by_version_id INTO next_id
        FROM knowledge_pack_versions
        WHERE id = next_id;
        EXIT WHEN next_id IS NULL;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Supersession is coherent for template versions too: superseded requires a
-- successor, assigning a successor transitions to superseded, same template only,
-- and successor must be a valid published successor. Retirement may have no successor.
CREATE OR REPLACE FUNCTION valid_task_template_version_supersession_check()
RETURNS TRIGGER AS $$
DECLARE
    successor_template_id INTEGER;
    successor_lifecycle TEXT;
    next_id INTEGER;
    visited INTEGER[];
BEGIN
    IF NEW.superseded_by_version_id IS NOT NULL THEN
        NEW.lifecycle_state_at_publish := 'superseded';
    END IF;

    IF NEW.lifecycle_state_at_publish = 'superseded' AND NEW.superseded_by_version_id IS NULL THEN
        RAISE EXCEPTION 'superseded task_template_versions must specify superseded_by_version_id'
            USING ERRCODE = 'check_violation';
    END IF;

    IF NEW.superseded_by_version_id IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.id = NEW.superseded_by_version_id THEN
        RAISE EXCEPTION 'task_template_versions cannot supersede itself'
            USING ERRCODE = 'check_violation';
    END IF;

    SELECT task_template_id, lifecycle_state_at_publish
    INTO successor_template_id, successor_lifecycle
    FROM task_template_versions
    WHERE id = NEW.superseded_by_version_id;

    IF successor_template_id IS NULL THEN
        RAISE EXCEPTION 'superseded_by_version_id must reference an existing task_template_versions row'
            USING ERRCODE = 'foreign_key_violation';
    END IF;

    IF successor_template_id IS DISTINCT FROM NEW.task_template_id THEN
        RAISE EXCEPTION 'superseded_by_version_id must belong to the same task_template (%)', NEW.task_template_id
            USING ERRCODE = 'check_violation';
    END IF;

    -- A new successor must currently be published.
    IF successor_lifecycle <> 'published' THEN
        RAISE EXCEPTION 'successor task_template_versions must be published, not %', successor_lifecycle
            USING ERRCODE = 'check_violation';
    END IF;

    -- Cycle detection: follow the successor chain from the proposed successor.
    -- If it leads back to the current row, the assignment would create a cycle.
    next_id := NEW.superseded_by_version_id;
    visited := ARRAY[NEW.id];
    LOOP
        IF next_id = ANY(visited) THEN
            RAISE EXCEPTION 'supersession assignment would create a cycle involving task_template_versions %', NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
        visited := array_append(visited, next_id);
        SELECT superseded_by_version_id INTO next_id
        FROM task_template_versions
        WHERE id = next_id;
        EXIT WHEN next_id IS NULL;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_knowledge_pack_versions_valid_supersession
    ON knowledge_pack_versions;
DROP TRIGGER IF EXISTS trg_task_template_versions_valid_supersession
    ON task_template_versions;

CREATE TRIGGER trg_knowledge_pack_versions_valid_supersession
    BEFORE INSERT OR UPDATE ON knowledge_pack_versions
    FOR EACH ROW
    EXECUTE FUNCTION valid_pack_version_supersession_check();

CREATE TRIGGER trg_task_template_versions_valid_supersession
    BEFORE INSERT OR UPDATE ON task_template_versions
    FOR EACH ROW
    EXECUTE FUNCTION valid_task_template_version_supersession_check();

-- ============================================================
-- Immutability enforcement for published knowledge versions
-- ============================================================

-- Helper function: enforce that published/superseded/retired knowledge versions
-- cannot change their content. Only a single supersession/retirement metadata
-- transition is permitted from the published state.
CREATE OR REPLACE FUNCTION immutable_version_update_check()
RETURNS TRIGGER AS $$
DECLARE
    lifecycle_col TEXT;
    old_lifecycle TEXT;
    new_lifecycle TEXT;
    allowed_cols TEXT[];
    key_name TEXT;
    old_val TEXT;
    new_val TEXT;
    disallowed_changed_cols TEXT[];
BEGIN
    -- Step versions are always immutable once created because they are
    -- published together with their parent template version.
    IF TG_TABLE_NAME = 'task_template_step_versions' THEN
        RAISE EXCEPTION 'task_template_step_versions are immutable and cannot be updated'
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    -- Determine the lifecycle column name for this table.
    IF TG_TABLE_NAME = 'knowledge_pack_versions' THEN
        lifecycle_col := 'lifecycle_state';
        allowed_cols := ARRAY['superseded_by_version_id', 'effective_until', 'lifecycle_state'];
    ELSIF TG_TABLE_NAME = 'task_template_versions' THEN
        lifecycle_col := 'lifecycle_state_at_publish';
        allowed_cols := ARRAY['superseded_by_version_id', 'effective_until', 'lifecycle_state_at_publish', 'is_step_set_sealed'];
    ELSE
        RAISE EXCEPTION 'unexpected table for immutable_version_update_check: %', TG_TABLE_NAME;
    END IF;

    EXECUTE format('SELECT ($1).%I', lifecycle_col) INTO old_lifecycle USING OLD;
    EXECUTE format('SELECT ($1).%I', lifecycle_col) INTO new_lifecycle USING NEW;

    -- Once superseded or retired, no further updates of any kind are allowed.
    IF old_lifecycle IN ('superseded', 'retired') THEN
        RAISE EXCEPTION '% row is already % and cannot be updated', TG_TABLE_NAME, old_lifecycle
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    -- When published, only the single supersession/retirement transition is allowed.
    IF old_lifecycle = 'published' THEN
        FOR key_name IN
            SELECT k.key
            FROM jsonb_each(to_jsonb(OLD)) k
        LOOP
            IF key_name = ANY(allowed_cols) THEN
                CONTINUE;
            END IF;
            EXECUTE format('SELECT ($1).%I::text', key_name) INTO old_val USING OLD;
            EXECUTE format('SELECT ($1).%I::text', key_name) INTO new_val USING NEW;
            IF old_val IS DISTINCT FROM new_val THEN
                disallowed_changed_cols := array_append(disallowed_changed_cols, key_name);
            END IF;
        END LOOP;

        IF array_length(disallowed_changed_cols, 1) > 0 THEN
            RAISE EXCEPTION 'published % row is immutable; disallowed changes: %', TG_TABLE_NAME, disallowed_changed_cols
                USING ERRCODE = 'insufficient_privilege';
        END IF;

        IF new_lifecycle IS DISTINCT FROM old_lifecycle THEN
            IF new_lifecycle NOT IN ('superseded', 'retired') THEN
                RAISE EXCEPTION 'published % may only transition % to superseded or retired, not %',
                    TG_TABLE_NAME, lifecycle_col, new_lifecycle
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Helper function: block deletion of published/superseded/retired versions.
CREATE OR REPLACE FUNCTION immutable_version_delete_check()
RETURNS TRIGGER AS $$
DECLARE
    lifecycle_col TEXT;
    old_lifecycle TEXT;
BEGIN
    IF TG_TABLE_NAME = 'knowledge_pack_versions' THEN
        lifecycle_col := 'lifecycle_state';
    ELSIF TG_TABLE_NAME = 'task_template_versions' THEN
        lifecycle_col := 'lifecycle_state_at_publish';
    ELSIF TG_TABLE_NAME = 'task_template_step_versions' THEN
        RAISE EXCEPTION 'task_template_step_versions are immutable and cannot be deleted'
            USING ERRCODE = 'insufficient_privilege';
    ELSE
        RAISE EXCEPTION 'unexpected table for immutable_version_delete_check: %', TG_TABLE_NAME;
    END IF;

    EXECUTE format('SELECT ($1).%I', lifecycle_col) INTO old_lifecycle USING OLD;

    IF old_lifecycle IN ('published', 'superseded', 'retired') THEN
        RAISE EXCEPTION 'published or retired % cannot be deleted', TG_TABLE_NAME
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Drop and recreate triggers to keep the migration idempotent.
-- Triggers fire on every UPDATE/DELETE; the functions decide whether to allow.
DROP TRIGGER IF EXISTS trg_knowledge_pack_versions_immutable_update ON knowledge_pack_versions;
DROP TRIGGER IF EXISTS trg_knowledge_pack_versions_immutable_delete ON knowledge_pack_versions;
DROP TRIGGER IF EXISTS trg_task_template_versions_immutable_update ON task_template_versions;
DROP TRIGGER IF EXISTS trg_task_template_versions_immutable_delete ON task_template_versions;
DROP TRIGGER IF EXISTS trg_task_template_step_versions_immutable_update ON task_template_step_versions;
DROP TRIGGER IF EXISTS trg_task_template_step_versions_immutable_delete ON task_template_step_versions;

CREATE TRIGGER trg_knowledge_pack_versions_immutable_update
    BEFORE UPDATE ON knowledge_pack_versions
    FOR EACH ROW
    EXECUTE FUNCTION immutable_version_update_check();

CREATE TRIGGER trg_knowledge_pack_versions_immutable_delete
    BEFORE DELETE ON knowledge_pack_versions
    FOR EACH ROW
    EXECUTE FUNCTION immutable_version_delete_check();

CREATE TRIGGER trg_task_template_versions_immutable_update
    BEFORE UPDATE ON task_template_versions
    FOR EACH ROW
    EXECUTE FUNCTION immutable_version_update_check();

CREATE TRIGGER trg_task_template_versions_immutable_delete
    BEFORE DELETE ON task_template_versions
    FOR EACH ROW
    EXECUTE FUNCTION immutable_version_delete_check();

CREATE TRIGGER trg_task_template_step_versions_immutable_update
    BEFORE UPDATE ON task_template_step_versions
    FOR EACH ROW
    EXECUTE FUNCTION immutable_version_update_check();

CREATE TRIGGER trg_task_template_step_versions_immutable_delete
    BEFORE DELETE ON task_template_step_versions
    FOR EACH ROW
    EXECUTE FUNCTION immutable_version_delete_check();

-- ============================================================
-- Irreversible step-set seal for template versions
-- ============================================================
-- The step-set seal may only move FALSE -> TRUE. Once TRUE, it cannot be
-- reverted. A seal is only permitted when at least one step version exists,
-- and a template version may never be committed as published unless sealed.

CREATE OR REPLACE FUNCTION task_template_version_seal_check()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- A version must be assembled unsealed and sealed only after steps are added.
        IF NEW.is_step_set_sealed = TRUE THEN
            RAISE EXCEPTION 'cannot insert task_template_versions with is_step_set_sealed = TRUE; add steps and seal via UPDATE'
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;

    -- TG_OP = 'UPDATE'
    -- Revert is forbidden.
    IF OLD.is_step_set_sealed = TRUE AND NEW.is_step_set_sealed = FALSE THEN
        RAISE EXCEPTION 'is_step_set_sealed cannot be changed from TRUE to FALSE for task_template_versions'
            USING ERRCODE = 'check_violation';
    END IF;

    -- Seal requires at least one step version.
    IF OLD.is_step_set_sealed = FALSE AND NEW.is_step_set_sealed = TRUE THEN
        IF NOT EXISTS (
            SELECT 1 FROM task_template_step_versions
            WHERE task_template_version_id = NEW.id
        ) THEN
            RAISE EXCEPTION 'cannot seal task_template_version % without at least one task_template_step_versions row', NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_task_template_versions_seal_check
    ON task_template_versions;

CREATE TRIGGER trg_task_template_versions_seal_check
    BEFORE INSERT OR UPDATE ON task_template_versions
    FOR EACH ROW
    EXECUTE FUNCTION task_template_version_seal_check();

-- ============================================================
-- Seal the complete template step set
-- ============================================================
-- A published task_template_version owns a complete, ordered set of
-- task_template_step_versions. Once the parent version is published and its
-- step set is sealed, no INSERT, UPDATE, or DELETE against that step set
-- is permitted. The seal is set by application code when the complete step set
-- is committed; until then the version may remain in a draft assembly state.
--
-- This is intentionally a low-level guard, not a full governance workflow.

CREATE OR REPLACE FUNCTION seal_template_step_set_check()
RETURNS TRIGGER AS $$
DECLARE
    parent_sealed BOOLEAN;
    parent_lifecycle TEXT;
    expected_template_id INTEGER;
    actual_template_id INTEGER;
BEGIN
    IF TG_OP IN ('UPDATE','DELETE') THEN
        SELECT v.is_step_set_sealed, v.lifecycle_state_at_publish
        INTO parent_sealed, parent_lifecycle
        FROM task_template_versions v
        WHERE v.id = OLD.task_template_version_id;

        IF parent_sealed THEN
            RAISE EXCEPTION 'task_template_step_versions for sealed template version % cannot be %',
                OLD.task_template_version_id, TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END IF;
    ELSIF TG_OP = 'INSERT' THEN
        SELECT v.is_step_set_sealed, v.lifecycle_state_at_publish, v.task_template_id
        INTO parent_sealed, parent_lifecycle, expected_template_id
        FROM task_template_versions v
        WHERE v.id = NEW.task_template_version_id;

        IF parent_sealed THEN
            RAISE EXCEPTION 'cannot add task_template_step_versions to sealed immutable template version %',
                NEW.task_template_version_id
                USING ERRCODE = 'insufficient_privilege';
        END IF;

        -- Source-step ancestry: the referenced task_template_steps row must
        -- belong to the same logical template as the parent version.
        SELECT s.task_template_id INTO actual_template_id
        FROM task_template_steps s
        WHERE s.id = NEW.task_template_step_id;

        IF actual_template_id IS DISTINCT FROM expected_template_id THEN
            RAISE EXCEPTION 'task_template_step_id % does not belong to task_template_id % for task_template_version %',
                NEW.task_template_step_id, expected_template_id, NEW.task_template_version_id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_task_template_step_versions_sealed_check
    ON task_template_step_versions;

CREATE TRIGGER trg_task_template_step_versions_sealed_check
    BEFORE INSERT OR UPDATE OR DELETE ON task_template_step_versions
    FOR EACH ROW
    EXECUTE FUNCTION seal_template_step_set_check();
