-- ATM-013F1 — Knowledge Provenance Foundation
-- Adds normalized source, source-version, and evidence association tables for
-- governed Atiman knowledge. Evidence supports working records during draft/review
-- and is frozen with published versions at seal time.
--
-- Scope:
-- - knowledge_sources: stable source identity (manuals, standards, procedures,
--   regulators, legacy migrations, engineering-authored knowledge).
-- - knowledge_source_versions: immutable exact revision/citation of a source.
-- - knowledge_template_evidence: editable working provenance for task_templates
--   and task_template_steps.
-- - knowledge_template_version_evidence: frozen published provenance for
--   task_template_versions and task_template_step_versions.
--
-- Out of scope (explicitly deferred):
-- - AI as a source type (AI remains derivation/version metadata only).
-- - JSON provenance blobs.
-- - Polymorphic subject references.
-- - Knowledge pack membership.
-- - Governance event table.
-- - Operational finding/inspection evidence.
-- - Legacy backfill of existing seeds.
-- - Publish-time copy service logic.
--
-- Idempotent deployment: CREATE IF NOT EXISTS / DROP IF NOT EXISTS throughout.

-- ============================================================
-- knowledge_sources: stable source identity
-- ============================================================
CREATE TABLE IF NOT EXISTS knowledge_sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_code VARCHAR(100) NOT NULL,
    source_category VARCHAR(50) NOT NULL
        CONSTRAINT chk_knowledge_sources_source_category
        CHECK (source_category IN (
            'manufacturer_manual',
            'engineering_standard',
            'internal_standard',
            'regulatory_source',
            'legacy_migration',
            'engineering_authored'
        )),
    default_title VARCHAR(500) NOT NULL,
    issuing_organization VARCHAR(255) DEFAULT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    organization_id INTEGER DEFAULT NULL,
    created_by_user_id INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    -- Tenant/global scoped uniqueness. NULL organization_id represents global/system
    -- sources; a tenant may reuse a code only within its own scope.
    CONSTRAINT uq_knowledge_sources_code_org
        UNIQUE NULLS NOT DISTINCT (organization_id, source_code),
    CONSTRAINT fk_knowledge_sources_organization
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_sources_created_by_user
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================================
-- knowledge_source_versions: immutable exact source revision/citation
-- ============================================================
CREATE TABLE IF NOT EXISTS knowledge_source_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    knowledge_source_id INTEGER NOT NULL,
    version_designation VARCHAR(100) NOT NULL,
    title VARCHAR(500) NOT NULL,
    reference_number VARCHAR(255) DEFAULT NULL,
    issuing_organization VARCHAR(255) DEFAULT NULL,
    publication_date DATE DEFAULT NULL,
    effective_date DATE DEFAULT NULL,
    uploaded_file_id INTEGER DEFAULT NULL,
    external_uri TEXT DEFAULT NULL,
    content_sha256 VARCHAR(64) DEFAULT NULL,
    created_by_user_id INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_knowledge_source_versions_source_version
        UNIQUE (knowledge_source_id, version_designation),
    CONSTRAINT fk_knowledge_source_versions_source
        FOREIGN KEY (knowledge_source_id) REFERENCES knowledge_sources(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_source_versions_uploaded_file
        FOREIGN KEY (uploaded_file_id) REFERENCES uploaded_files(id) ON DELETE SET NULL,
    CONSTRAINT fk_knowledge_source_versions_created_by_user
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================================
-- knowledge_template_evidence: editable working provenance
-- ============================================================
CREATE TABLE IF NOT EXISTS knowledge_template_evidence (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_id INTEGER DEFAULT NULL,
    task_template_step_id INTEGER DEFAULT NULL,
    knowledge_source_version_id INTEGER NOT NULL,
    section_or_clause VARCHAR(255) DEFAULT NULL,
    page_or_paragraph VARCHAR(255) DEFAULT NULL,
    derivation_notes TEXT DEFAULT NULL,
    confidence_level VARCHAR(50) NOT NULL DEFAULT 'provisional'
        CONSTRAINT chk_knowledge_template_evidence_confidence
        CHECK (confidence_level IN ('established', 'provisional', 'experimental', 'uncertain')),
    supporting_role VARCHAR(50) NOT NULL DEFAULT 'supporting'
        CONSTRAINT chk_knowledge_template_evidence_role
        CHECK (supporting_role IN ('primary', 'supporting')),
    added_by_user_id INTEGER DEFAULT NULL,
    added_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    -- Exactly one subject: a working evidence row belongs to either a template
    -- or a step, never both, never neither.
    CONSTRAINT chk_knowledge_template_evidence_exactly_one_subject
        CHECK (
            (task_template_id IS NOT NULL AND task_template_step_id IS NULL)
            OR
            (task_template_id IS NULL AND task_template_step_id IS NOT NULL)
        ),
    CONSTRAINT fk_knowledge_template_evidence_template
        FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_template_evidence_step
        FOREIGN KEY (task_template_step_id) REFERENCES task_template_steps(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_template_evidence_source_version
        FOREIGN KEY (knowledge_source_version_id) REFERENCES knowledge_source_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_template_evidence_added_by_user
        FOREIGN KEY (added_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================================
-- knowledge_template_version_evidence: frozen published provenance
-- ============================================================
CREATE TABLE IF NOT EXISTS knowledge_template_version_evidence (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_version_id INTEGER DEFAULT NULL,
    task_template_step_version_id INTEGER DEFAULT NULL,
    knowledge_source_version_id INTEGER NOT NULL,
    section_or_clause VARCHAR(255) DEFAULT NULL,
    page_or_paragraph VARCHAR(255) DEFAULT NULL,
    derivation_notes TEXT DEFAULT NULL,
    confidence_level VARCHAR(50) NOT NULL DEFAULT 'provisional'
        CONSTRAINT chk_knowledge_template_version_evidence_confidence
        CHECK (confidence_level IN ('established', 'provisional', 'experimental', 'uncertain')),
    supporting_role VARCHAR(50) NOT NULL DEFAULT 'supporting'
        CONSTRAINT chk_knowledge_template_version_evidence_role
        CHECK (supporting_role IN ('primary', 'supporting')),
    copied_from_template_evidence_id INTEGER DEFAULT NULL,
    added_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    -- Exactly one subject: a published evidence row belongs to either a template
    -- version or a step version, never both, never neither.
    CONSTRAINT chk_knowledge_template_version_evidence_exactly_one_subject
        CHECK (
            (task_template_version_id IS NOT NULL AND task_template_step_version_id IS NULL)
            OR
            (task_template_version_id IS NULL AND task_template_step_version_id IS NOT NULL)
        ),
    CONSTRAINT fk_knowledge_template_version_evidence_template_version
        FOREIGN KEY (task_template_version_id) REFERENCES task_template_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_template_version_evidence_step_version
        FOREIGN KEY (task_template_step_version_id) REFERENCES task_template_step_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_template_version_evidence_source_version
        FOREIGN KEY (knowledge_source_version_id) REFERENCES knowledge_source_versions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_template_version_evidence_copied_from
        FOREIGN KEY (copied_from_template_evidence_id) REFERENCES knowledge_template_evidence(id) ON DELETE SET NULL
);

-- ============================================================
-- Indexes for provenance tables
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_knowledge_sources_org_code
    ON knowledge_sources (organization_id, source_code);

CREATE INDEX IF NOT EXISTS idx_knowledge_source_versions_source
    ON knowledge_source_versions (knowledge_source_id, version_designation);

CREATE INDEX IF NOT EXISTS idx_knowledge_template_evidence_template
    ON knowledge_template_evidence (task_template_id)
    WHERE task_template_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_knowledge_template_evidence_step
    ON knowledge_template_evidence (task_template_step_id)
    WHERE task_template_step_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_knowledge_template_version_evidence_template_version
    ON knowledge_template_version_evidence (task_template_version_id)
    WHERE task_template_version_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_knowledge_template_version_evidence_step_version
    ON knowledge_template_version_evidence (task_template_step_version_id)
    WHERE task_template_step_version_id IS NOT NULL;

-- ============================================================
-- Immutability: knowledge_source_versions must not be updated or deleted
-- once referenced by evidence. We enforce no UPDATE on the row and no DELETE
-- when it has dependent evidence rows.
-- ============================================================
CREATE OR REPLACE FUNCTION immutable_source_version_check()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'knowledge_source_versions are immutable and cannot be updated'
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    IF TG_OP = 'DELETE' THEN
        IF EXISTS (
            SELECT 1 FROM knowledge_template_evidence
            WHERE knowledge_source_version_id = OLD.id
        ) OR EXISTS (
            SELECT 1 FROM knowledge_template_version_evidence
            WHERE knowledge_source_version_id = OLD.id
        ) THEN
            RAISE EXCEPTION 'knowledge_source_version % is referenced by evidence and cannot be deleted', OLD.id
                USING ERRCODE = 'foreign_key_violation';
        END IF;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_knowledge_source_versions_immutable
    ON knowledge_source_versions;

CREATE TRIGGER trg_knowledge_source_versions_immutable
    BEFORE UPDATE OR DELETE ON knowledge_source_versions
    FOR EACH ROW
    EXECUTE FUNCTION immutable_source_version_check();

-- ============================================================
-- Immutability: frozen published evidence must not be updated or deleted.
-- ============================================================
CREATE OR REPLACE FUNCTION immutable_template_version_evidence_check()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'knowledge_template_version_evidence is immutable and cannot be %', TG_OP
        USING ERRCODE = 'insufficient_privilege';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_knowledge_template_version_evidence_immutable
    ON knowledge_template_version_evidence;

CREATE TRIGGER trg_knowledge_template_version_evidence_immutable
    BEFORE UPDATE OR DELETE ON knowledge_template_version_evidence
    FOR EACH ROW
    EXECUTE FUNCTION immutable_template_version_evidence_check();
