-- ATM-013F2A — Task Template Safety Control Versioning
-- Adds immutable safety-control versions that belong to a published
-- task_template_version, mirroring the step-version pattern established in
-- migration 009.
--
-- Scope:
-- - task_template_safety_control_versions: one immutable row per
--   task_template_safety_controls row at publish time.
--
-- Out of scope (explicitly deferred):
-- - Publication service logic.
-- - Controller/route changes.
-- - Knowledge pack membership.
-- - Legacy backfill of existing safety controls.
--
-- Idempotent deployment: CREATE IF NOT EXISTS / DROP IF NOT EXISTS throughout.

-- ============================================================
-- task_template_safety_control_versions
-- Immutable safety-control copy frozen with a task_template_version.
-- ============================================================
CREATE TABLE IF NOT EXISTS task_template_safety_control_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_version_id INTEGER NOT NULL,
    task_template_safety_control_id INTEGER NOT NULL,
    safety_type VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    is_mandatory BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_task_template_safety_control_versions_version_source
        UNIQUE (task_template_version_id, task_template_safety_control_id),
    CONSTRAINT fk_task_template_safety_control_versions_template_version
        FOREIGN KEY (task_template_version_id) REFERENCES task_template_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_template_safety_control_versions_source
        FOREIGN KEY (task_template_safety_control_id) REFERENCES task_template_safety_controls(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_task_template_safety_control_versions_version_id
    ON task_template_safety_control_versions (task_template_version_id);

CREATE INDEX IF NOT EXISTS idx_task_template_safety_control_versions_source_id
    ON task_template_safety_control_versions (task_template_safety_control_id);

-- ============================================================
-- Immutability + seal guard for safety-control versions
-- A safety-control version is part of the published template version. It must
-- not be inserted after the parent version is sealed, and it must never be
-- updated or deleted once created.
-- ============================================================
CREATE OR REPLACE FUNCTION task_template_safety_control_versions_guard()
RETURNS TRIGGER AS $$
DECLARE
    parent_sealed BOOLEAN;
    expected_template_id INTEGER;
    actual_template_id INTEGER;
BEGIN
    IF TG_OP IN ('UPDATE','DELETE') THEN
        -- Safety-control versions are immutable once created.
        RAISE EXCEPTION 'task_template_safety_control_versions are immutable and cannot be %', TG_OP
            USING ERRCODE = 'insufficient_privilege';
    ELSIF TG_OP = 'INSERT' THEN
        -- Parent must still be unsealed so all publication records form one
        -- atomic, consistent snapshot.
        SELECT v.is_step_set_sealed, v.task_template_id
        INTO parent_sealed, expected_template_id
        FROM task_template_versions v
        WHERE v.id = NEW.task_template_version_id;

        IF parent_sealed THEN
            RAISE EXCEPTION 'cannot add task_template_safety_control_versions to sealed template version %',
                NEW.task_template_version_id
                USING ERRCODE = 'insufficient_privilege';
        END IF;

        -- Source-control ancestry: the referenced safety control must belong to
        -- the same logical task template as the parent version.
        SELECT sc.task_template_id INTO actual_template_id
        FROM task_template_safety_controls sc
        WHERE sc.id = NEW.task_template_safety_control_id;

        IF actual_template_id IS DISTINCT FROM expected_template_id THEN
            RAISE EXCEPTION 'task_template_safety_control_id % does not belong to task_template_id % for task_template_version %',
                NEW.task_template_safety_control_id, expected_template_id, NEW.task_template_version_id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_task_template_safety_control_versions_guard
    ON task_template_safety_control_versions;

CREATE TRIGGER trg_task_template_safety_control_versions_guard
    BEFORE INSERT OR UPDATE OR DELETE ON task_template_safety_control_versions
    FOR EACH ROW
    EXECUTE FUNCTION task_template_safety_control_versions_guard();
